// Apps/UltraWeb/host/UltraWebDemoApp.h
// GENERATED by generate_demo_app.py - edit that, not this.
// about:demo, the app UltraWeb ships with: a WebAssembly module in text
// form that exercises element ABI v1 (UltraWeb/guest/ultraweb.h) - labels,
// a button counting clicks, a text input echoed into a label, a checkbox
// showing and hiding an element. WasmHost compiles the text itself, so it
// needs no wasm toolchain to build, and the UltraWeb tests run it too.
#pragma once

namespace UltraWeb {

inline const char* DemoAppWat() {
    return R"WAT(
(module
  (import "ultracanvas" "uc_create" (func $create (param i32 i32) (result i32)))
  (import "ultracanvas" "uc_insert" (func $insert (param i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_set_text" (func $set_text (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_set_number" (func $set_number (param i32 i32 f64) (result i32)))
  (import "ultracanvas" "uc_get_text" (func $get_text (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_listen" (func $listen (param i32 i32) (result i32)))
  (import "ultracanvas" "uc_log" (func $log (param i32 i32)))
  (memory (export "memory") 1)
  (data (i32.const 0) "Container")
  (data (i32.const 16) "Label")
  (data (i32.const 32) "Button")
  (data (i32.const 48) "TextInput")
  (data (i32.const 64) "Checkbox")
  (data (i32.const 80) "Hello from WebAssembly")
  (data (i32.const 112) "This page is a small WebAssembly module, written by hand in WebAssembly text. Every control below is a real UltraCanvas element that UltraWeb created for it through the element ABI; the module only holds handles.")
  (data (i32.const 336) "Count")
  (data (i32.const 352) "Clicked ")
  (data (i32.const 368) " times")
  (data (i32.const 384) "Type something")
  (data (i32.const 400) "You typed: ")
  (data (i32.const 416) "You typed: nothing yet")
  (data (i32.const 448) "Show the counter")
  (data (i32.const 464) "about:demo started")
  (global $count (mut i32) (i32.const 0))
  (global $button (mut i32) (i32.const 0))
  (global $counter (mut i32) (i32.const 0))
  (global $input (mut i32) (i32.const 0))
  (global $echo (mut i32) (i32.const 0))
  (global $check (mut i32) (i32.const 0))

  ;; A new element of a kind, inserted at the end of a parent.
  (func $add (param $parent i32) (param $kind i32) (param $kindLength i32) (result i32)
    (local $h i32)
    (local.set $h (call $create (local.get $kind) (local.get $kindLength)))
    (drop (call $insert (local.get $parent) (local.get $h) (i32.const 0)))
    (local.get $h))

  (func $text (param $h i32) (param $ptr i32) (param $length i32)
    (drop (call $set_text (local.get $h) (i32.const 1) (local.get $ptr) (local.get $length))))

  ;; Decimal digits of a non-negative value at dst; returns their count.
  (func $digits (param $value i32) (param $dst i32) (result i32)
    (local $n i32) (local $i i32) (local $t i32)
    (loop $emit
      (i32.store8 (i32.add (local.get $dst) (local.get $n))
                  (i32.add (i32.const 48) (i32.rem_u (local.get $value) (i32.const 10))))
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (local.set $value (i32.div_u (local.get $value) (i32.const 10)))
      (br_if $emit (local.get $value)))
    ;; reverse in place
    (local.set $i (i32.const 0))
    (block $done
      (loop $swap
        (br_if $done (i32.ge_u (local.get $i) (i32.div_u (local.get $n) (i32.const 2))))
        (local.set $t (i32.load8_u (i32.add (local.get $dst) (local.get $i))))
        (i32.store8 (i32.add (local.get $dst) (local.get $i))
                    (i32.load8_u (i32.add (local.get $dst) (i32.sub (i32.sub (local.get $n) (i32.const 1)) (local.get $i)))))
        (i32.store8 (i32.add (local.get $dst) (i32.sub (i32.sub (local.get $n) (i32.const 1)) (local.get $i))) (local.get $t))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $swap)))
    (local.get $n))

  ;; "Clicked N times" into the counter label.
  (func $show_count
    (local $length i32)
    (memory.copy (i32.const 4096) (i32.const 352) (i32.const 8))
    (local.set $length (i32.add (i32.const 8)
      (call $digits (global.get $count) (i32.const 4104))))
    (memory.copy (i32.add (i32.const 4096) (local.get $length)) (i32.const 368) (i32.const 6))
    (local.set $length (i32.add (local.get $length) (i32.const 6)))
    (call $text (global.get $counter) (i32.const 4096) (local.get $length)))

  (func (export "uc_main")
    (local $h i32) (local $row i32)
    (call $log (i32.const 464) (i32.const 18))
    ;; The root: a padded column.
    (drop (call $set_number (i32.const 1) (i32.const 10) (f64.const 10)))
    (drop (call $set_number (i32.const 1) (i32.const 11) (f64.const 16)))

    (local.set $h (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (local.get $h) (i32.const 80) (i32.const 22))
    (drop (call $set_number (local.get $h) (i32.const 12) (f64.const 18)))

    (local.set $h (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (local.get $h) (i32.const 112) (i32.const 212))

    ;; A row: the button and the count beside it.
    (local.set $row (call $add (i32.const 1) (i32.const 0) (i32.const 9)))
    (drop (call $set_number (local.get $row) (i32.const 9) (f64.const 1)))
    (drop (call $set_number (local.get $row) (i32.const 10) (f64.const 12)))
    (global.set $button (call $add (local.get $row) (i32.const 32) (i32.const 6)))
    (call $text (global.get $button) (i32.const 336) (i32.const 5))
    (drop (call $listen (global.get $button) (i32.const 1)))
    (global.set $counter (call $add (local.get $row) (i32.const 16) (i32.const 5)))
    (drop (call $set_number (global.get $counter) (i32.const 8) (f64.const 1)))
    (call $show_count)

    (global.set $input (call $add (i32.const 1) (i32.const 48) (i32.const 9)))
    (drop (call $set_text (global.get $input) (i32.const 2) (i32.const 384) (i32.const 14)))
    (drop (call $listen (global.get $input) (i32.const 2)))
    (global.set $echo (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (global.get $echo) (i32.const 416) (i32.const 22))

    (global.set $check (call $add (i32.const 1) (i32.const 64) (i32.const 8)))
    (call $text (global.get $check) (i32.const 448) (i32.const 16))
    (drop (call $set_number (global.get $check) (i32.const 3) (f64.const 1)))
    (drop (call $listen (global.get $check) (i32.const 8))))

  (func (export "uc_event") (param $h i32) (param $event i32) (param $detail i32)
    (local $length i32)
    ;; Count clicks.
    (if (i32.and (i32.eq (local.get $h) (global.get $button)) (i32.eq (local.get $event) (i32.const 1)))
      (then
        (global.set $count (i32.add (global.get $count) (i32.const 1)))
        (call $show_count)))
    ;; Echo the input: its text straight after the prefix.
    (if (i32.and (i32.eq (local.get $h) (global.get $input)) (i32.eq (local.get $event) (i32.const 2)))
      (then
        (memory.copy (i32.const 4096) (i32.const 400) (i32.const 11))
        (local.set $length (call $get_text (global.get $input) (i32.const 1)
                                           (i32.const 4107) (i32.const 1024)))
        (if (i32.gt_u (local.get $length) (i32.const 1024)) (then (local.set $length (i32.const 1024))))
        (if (i32.lt_s (local.get $length) (i32.const 0)) (then (local.set $length (i32.const 0))))
        (call $text (global.get $echo) (i32.const 4096) (i32.add (local.get $length) (i32.const 11)))))
    ;; The checkbox shows or hides the count.
    (if (i32.and (i32.eq (local.get $h) (global.get $check)) (i32.eq (local.get $event) (i32.const 8)))
      (then
        (drop (call $set_number (global.get $counter) (i32.const 5) (f64.convert_i32_s (local.get $detail))))))))
)WAT";
}

} // namespace UltraWeb
