// Apps/UltraWeb/host/UltraWebDemoApp.h
// GENERATED by generate_demo_app.py - edit that, not this.
// about:demo, the app UltraWeb ships with: a WebAssembly module in text
// form that exercises the element ABI (UltraWeb/guest/ultraweb.h) - labels,
// a button counting clicks into storage, a text input echoed into a label
// and copied to the clipboard, a checkbox showing and hiding an element, a
// timer counting seconds. WasmHost compiles the text itself, so it
// needs no wasm toolchain to build, and the UltraWeb tests run it too.
#pragma once

namespace UltraWeb {

inline const char* DemoAppWat() {
    return R"WAT(
(module
  (import "ultracanvas" "uc_create" (func $create (param i32 i32) (result i32)))
  (import "ultracanvas" "uc_insert" (func $insert (param i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_set_text" (func $set_text (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_set_number" (func $set_number (param i32 i32 f64) (result i32)))
  (import "ultracanvas" "uc_get_text" (func $get_text (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_listen" (func $listen (param i32 i32) (result i32)))
  (import "ultracanvas" "uc_log" (func $log (param i32 i32)))
  (import "ultracanvas" "uc_timer_start" (func $timer_start (param i32 i32) (result i32)))
  (import "ultracanvas" "uc_storage_get" (func $storage_get (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_storage_set" (func $storage_set (param i32 i32 i32 i32) (result i32)))
  (import "ultracanvas" "uc_clipboard_write" (func $clipboard_write (param i32 i32) (result i32)))
  (memory (export "memory") 1)
  (data (i32.const 0) "Container")
  (data (i32.const 16) "Label")
  (data (i32.const 32) "Button")
  (data (i32.const 48) "TextInput")
  (data (i32.const 64) "Checkbox")
  (data (i32.const 80) "Hello from WebAssembly")
  (data (i32.const 112) "This page is a small WebAssembly module, written by hand in WebAssembly text. Every control below is a real UltraCanvas element that UltraWeb created for it through the element ABI; the module only holds handles. It keeps its count in UltraWeb's storage, so the count survives a reload, and a timer tells how long it has run.")
  (data (i32.const 448) "Count")
  (data (i32.const 464) "Clicked ")
  (data (i32.const 480) " times")
  (data (i32.const 496) "Type something")
  (data (i32.const 512) "You typed: ")
  (data (i32.const 528) "You typed: nothing yet")
  (data (i32.const 560) "Show the counter")
  (data (i32.const 576) "about:demo started")
  (data (i32.const 608) "clicks")
  (data (i32.const 624) "Copy what you typed")
  (data (i32.const 656) "Copied to the clipboard")
  (data (i32.const 688) "The clipboard did not take it")
  (data (i32.const 720) "Running for ")
  (data (i32.const 736) " s")
  (global $count (mut i32) (i32.const 0))
  (global $button (mut i32) (i32.const 0))
  (global $counter (mut i32) (i32.const 0))
  (global $input (mut i32) (i32.const 0))
  (global $echo (mut i32) (i32.const 0))
  (global $check (mut i32) (i32.const 0))
  (global $copy (mut i32) (i32.const 0))
  (global $uptime (mut i32) (i32.const 0))
  (global $tick (mut i32) (i32.const 0))
  (global $seconds (mut i32) (i32.const 0))

  ;; Element ABI v2: timers, storage and the clipboard.
  (func (export "uc_abi_version") (result i32) (i32.const 2))

  ;; A new element of a kind, inserted at the end of a parent.
  (func $add (param $parent i32) (param $kind i32) (param $kindLength i32) (result i32)
    (local $h i32)
    (local.set $h (call $create (local.get $kind) (local.get $kindLength)))
    (drop (call $insert (local.get $parent) (local.get $h) (i32.const 0)))
    (local.get $h))

  (func $text (param $h i32) (param $ptr i32) (param $length i32)
    (drop (call $set_text (local.get $h) (i32.const 1) (local.get $ptr) (local.get $length))))

  ;; Decimal digits of a non-negative value at dst; returns their count.
  (func $digits (param $value i32) (param $dst i32) (result i32)
    (local $n i32) (local $i i32) (local $t i32)
    (loop $emit
      (i32.store8 (i32.add (local.get $dst) (local.get $n))
                  (i32.add (i32.const 48) (i32.rem_u (local.get $value) (i32.const 10))))
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (local.set $value (i32.div_u (local.get $value) (i32.const 10)))
      (br_if $emit (local.get $value)))
    ;; reverse in place
    (local.set $i (i32.const 0))
    (block $done
      (loop $swap
        (br_if $done (i32.ge_u (local.get $i) (i32.div_u (local.get $n) (i32.const 2))))
        (local.set $t (i32.load8_u (i32.add (local.get $dst) (local.get $i))))
        (i32.store8 (i32.add (local.get $dst) (local.get $i))
                    (i32.load8_u (i32.add (local.get $dst) (i32.sub (i32.sub (local.get $n) (i32.const 1)) (local.get $i)))))
        (i32.store8 (i32.add (local.get $dst) (i32.sub (i32.sub (local.get $n) (i32.const 1)) (local.get $i))) (local.get $t))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $swap)))
    (local.get $n))

  ;; "Clicked N times" into the counter label.
  (func $show_count
    (local $length i32)
    (memory.copy (i32.const 4096) (i32.const 464) (i32.const 8))
    (local.set $length (i32.add (i32.const 8)
      (call $digits (global.get $count) (i32.const 4104))))
    (memory.copy (i32.add (i32.const 4096) (local.get $length)) (i32.const 480) (i32.const 6))
    (local.set $length (i32.add (local.get $length) (i32.const 6)))
    (call $text (global.get $counter) (i32.const 4096) (local.get $length)))

  ;; "Running for N s" into the uptime label.
  (func $show_uptime
    (local $length i32)
    (memory.copy (i32.const 4096) (i32.const 720) (i32.const 12))
    (local.set $length (i32.add (i32.const 12)
      (call $digits (global.get $seconds) (i32.const 4108))))
    (memory.copy (i32.add (i32.const 4096) (local.get $length)) (i32.const 736) (i32.const 2))
    (local.set $length (i32.add (local.get $length) (i32.const 2)))
    (call $text (global.get $uptime) (i32.const 4096) (local.get $length)))

  ;; The count from storage, if an earlier run left one: up to 9 digits.
  (func $load_count
    (local $length i32) (local $i i32) (local $c i32) (local $value i32)
    (local.set $length (call $storage_get (i32.const 608) (i32.const 6) (i32.const 6144) (i32.const 16)))
    (if (i32.or (i32.lt_s (local.get $length) (i32.const 1)) (i32.gt_s (local.get $length) (i32.const 9))) (then (return)))
    (block $bad
      (loop $parse
        (local.set $c (i32.load8_u (i32.add (i32.const 6144) (local.get $i))))
        (br_if $bad (i32.or (i32.lt_u (local.get $c) (i32.const 48)) (i32.gt_u (local.get $c) (i32.const 57))))
        (local.set $value (i32.add (i32.mul (local.get $value) (i32.const 10)) (i32.sub (local.get $c) (i32.const 48))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $parse (i32.lt_u (local.get $i) (local.get $length))))
      (global.set $count (local.get $value))))

  (func $store_count
    (drop (call $storage_set (i32.const 608) (i32.const 6) (i32.const 6144)
                             (call $digits (global.get $count) (i32.const 6144)))))

  (func (export "uc_main")
    (local $h i32) (local $row i32)
    (call $log (i32.const 576) (i32.const 18))
    ;; The root: a padded column.
    (drop (call $set_number (i32.const 1) (i32.const 10) (f64.const 10)))
    (drop (call $set_number (i32.const 1) (i32.const 11) (f64.const 16)))

    (local.set $h (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (local.get $h) (i32.const 80) (i32.const 22))
    (drop (call $set_number (local.get $h) (i32.const 12) (f64.const 18)))

    (local.set $h (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (local.get $h) (i32.const 112) (i32.const 325))

    ;; A row: the button and the count beside it.
    (local.set $row (call $add (i32.const 1) (i32.const 0) (i32.const 9)))
    (drop (call $set_number (local.get $row) (i32.const 9) (f64.const 1)))
    (drop (call $set_number (local.get $row) (i32.const 10) (f64.const 12)))
    ;; The count beside the button, centred on it (UC_PROP_ALIGN center).
    (drop (call $set_number (local.get $row) (i32.const 15) (f64.const 1)))
    (global.set $button (call $add (local.get $row) (i32.const 32) (i32.const 6)))
    (call $text (global.get $button) (i32.const 448) (i32.const 5))
    (drop (call $listen (global.get $button) (i32.const 1)))
    (global.set $counter (call $add (local.get $row) (i32.const 16) (i32.const 5)))
    (drop (call $set_number (global.get $counter) (i32.const 8) (f64.const 1)))
    (call $load_count)
    (call $show_count)

    (global.set $input (call $add (i32.const 1) (i32.const 48) (i32.const 9)))
    (drop (call $set_text (global.get $input) (i32.const 2) (i32.const 496) (i32.const 14)))
    (drop (call $listen (global.get $input) (i32.const 2)))
    (global.set $echo (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $text (global.get $echo) (i32.const 528) (i32.const 22))

    (global.set $check (call $add (i32.const 1) (i32.const 64) (i32.const 8)))
    (call $text (global.get $check) (i32.const 560) (i32.const 16))
    (drop (call $set_number (global.get $check) (i32.const 3) (f64.const 1)))
    (drop (call $listen (global.get $check) (i32.const 8)))

    ;; The copy button goes between the input and its echo.
    (global.set $copy (call $create (i32.const 32) (i32.const 6)))
    (drop (call $insert (i32.const 1) (global.get $copy) (global.get $echo)))
    (call $text (global.get $copy) (i32.const 624) (i32.const 19))
    (drop (call $listen (global.get $copy) (i32.const 1)))

    ;; A second-by-second timer.
    (global.set $uptime (call $add (i32.const 1) (i32.const 16) (i32.const 5)))
    (call $show_uptime)
    (global.set $tick (call $timer_start (i32.const 1000) (i32.const 1))))

  (func (export "uc_event") (param $h i32) (param $event i32) (param $detail i32)
    (local $length i32)
    ;; Count clicks.
    (if (i32.and (i32.eq (local.get $h) (global.get $button)) (i32.eq (local.get $event) (i32.const 1)))
      (then
        (global.set $count (i32.add (global.get $count) (i32.const 1)))
        (call $show_count)
        (call $store_count)))
    ;; Copy the input's text; a click is a user action, so the clipboard takes it.
    (if (i32.and (i32.eq (local.get $h) (global.get $copy)) (i32.eq (local.get $event) (i32.const 1)))
      (then
        (local.set $length (call $get_text (global.get $input) (i32.const 1) (i32.const 8192) (i32.const 32768)))
        (if (i32.gt_u (local.get $length) (i32.const 32768)) (then (local.set $length (i32.const 32768))))
        (if (i32.lt_s (local.get $length) (i32.const 0)) (then (local.set $length (i32.const 0))))
        (if (i32.eqz (call $clipboard_write (i32.const 8192) (local.get $length)))
          (then (call $text (global.get $echo) (i32.const 656) (i32.const 23)))
          (else (call $text (global.get $echo) (i32.const 688) (i32.const 29))))))
    ;; The timer: handle 0 (no element), event 16, detail its id.
    (if (i32.and (i32.eqz (local.get $h)) (i32.and (i32.eq (local.get $event) (i32.const 16))
                                                  (i32.eq (local.get $detail) (global.get $tick))))
      (then
        (global.set $seconds (i32.add (global.get $seconds) (i32.const 1)))
        (call $show_uptime)))
    ;; Echo the input: its text straight after the prefix.
    (if (i32.and (i32.eq (local.get $h) (global.get $input)) (i32.eq (local.get $event) (i32.const 2)))
      (then
        (memory.copy (i32.const 4096) (i32.const 512) (i32.const 11))
        (local.set $length (call $get_text (global.get $input) (i32.const 1)
                                           (i32.const 4107) (i32.const 1024)))
        (if (i32.gt_u (local.get $length) (i32.const 1024)) (then (local.set $length (i32.const 1024))))
        (if (i32.lt_s (local.get $length) (i32.const 0)) (then (local.set $length (i32.const 0))))
        (call $text (global.get $echo) (i32.const 4096) (i32.add (local.get $length) (i32.const 11)))))
    ;; The checkbox shows or hides the count.
    (if (i32.and (i32.eq (local.get $h) (global.get $check)) (i32.eq (local.get $event) (i32.const 8)))
      (then
        (drop (call $set_number (global.get $counter) (i32.const 5) (f64.convert_i32_s (local.get $detail))))))))
)WAT";
}

} // namespace UltraWeb
