#!/usr/bin/env python3
"""
Procedural OBJ model generator for the UltraCanvas OpenGL "3D Models" demo tab.

Generates a small set of reasonably complex, smooth-shaded meshes with explicit
vertex normals so the demo's OBJ loader has something interesting to display:

    icosphere.obj   - subdivided icosahedron (smooth sphere)
    torusknot.obj   - (p=2, q=3) torus knot tube
    spring.obj      - helical coil tube

These files are committed to the repo so the demo loads real geometry from disk.
Re-run this script to regenerate them:  python3 generate_models.py
"""
import math


def write_obj(path, name, verts, normals, faces):
    with open(path, "w") as f:
        f.write(f"# {name} - generated by generate_models.py for the UltraCanvas 3D demo\n")
        f.write(f"# {len(verts)} vertices, {len(faces)} triangles\n")
        f.write(f"o {name}\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for n in normals:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        for a, b, c in faces:
            # OBJ is 1-indexed; v//vn form (no texcoords)
            f.write(f"f {a+1}//{a+1} {b+1}//{b+1} {c+1}//{c+1}\n")
    print(f"wrote {path}: {len(verts)} verts, {len(faces)} tris")


def normalize(v):
    l = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    if l < 1e-9:
        return (0.0, 0.0, 0.0)
    return (v[0] / l, v[1] / l, v[2] / l)


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def smooth_normals(verts, faces):
    normals = [(0.0, 0.0, 0.0)] * len(verts)
    for a, b, c in faces:
        fn = cross(sub(verts[b], verts[a]), sub(verts[c], verts[a]))
        for idx in (a, b, c):
            normals[idx] = add(normals[idx], fn)
    return [normalize(n) for n in normals]


# ---------------------------------------------------------------- icosphere
def gen_icosphere(subdiv=3, radius=1.0):
    t = (1.0 + math.sqrt(5.0)) / 2.0
    base = [
        (-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
        (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
        (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1),
    ]
    verts = [list(normalize(v)) for v in base]
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    cache = {}

    def midpoint(i, j):
        key = (min(i, j), max(i, j))
        if key in cache:
            return cache[key]
        m = normalize(((verts[i][0] + verts[j][0]) / 2,
                       (verts[i][1] + verts[j][1]) / 2,
                       (verts[i][2] + verts[j][2]) / 2))
        verts.append(list(m))
        cache[key] = len(verts) - 1
        return cache[key]

    for _ in range(subdiv):
        new_faces = []
        for a, b, c in faces:
            ab = midpoint(a, b)
            bc = midpoint(b, c)
            ca = midpoint(c, a)
            new_faces += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = new_faces

    verts = [(v[0] * radius, v[1] * radius, v[2] * radius) for v in verts]
    normals = [normalize(v) for v in verts]  # sphere normal == position dir
    return verts, normals, faces


# ---------------------------------------------------------------- torus knot
def gen_torusknot(p=2, q=3, tube_segments=240, radial_segments=24,
                  scale=0.55, tube_radius=0.28):
    def knot_point(u):
        # u in [0, 2pi)
        r = math.cos(q * u) + 2.0
        x = r * math.cos(p * u)
        y = r * math.sin(p * u)
        z = -math.sin(q * u)
        return (x * scale, y * scale, z * scale)

    verts = []
    faces = []
    eps = 1e-3
    for i in range(tube_segments):
        u = 2.0 * math.pi * i / tube_segments
        cur = knot_point(u)
        nxt = knot_point(u + eps)
        tangent = normalize(sub(nxt, cur))
        # build a frame
        helper = (0.0, 0.0, 1.0)
        if abs(tangent[2]) > 0.9:
            helper = (0.0, 1.0, 0.0)
        normal = normalize(cross(tangent, helper))
        binormal = normalize(cross(tangent, normal))
        for j in range(radial_segments):
            v = 2.0 * math.pi * j / radial_segments
            cx = math.cos(v) * tube_radius
            cy = math.sin(v) * tube_radius
            px = cur[0] + cx * normal[0] + cy * binormal[0]
            py = cur[1] + cx * normal[1] + cy * binormal[1]
            pz = cur[2] + cx * normal[2] + cy * binormal[2]
            verts.append((px, py, pz))

    for i in range(tube_segments):
        for j in range(radial_segments):
            a = i * radial_segments + j
            b = i * radial_segments + (j + 1) % radial_segments
            ni = (i + 1) % tube_segments
            c = ni * radial_segments + j
            d = ni * radial_segments + (j + 1) % radial_segments
            faces.append((a, c, b))
            faces.append((b, c, d))

    normals = smooth_normals(verts, faces)
    return verts, normals, faces


# ---------------------------------------------------------------- spring/coil
def gen_spring(coils=4, turn_segments=64, radial_segments=18,
               coil_radius=0.7, tube_radius=0.16, height=1.6):
    tube_segments = coils * turn_segments

    def center(t):
        # t in [0,1]
        ang = 2.0 * math.pi * coils * t
        x = coil_radius * math.cos(ang)
        z = coil_radius * math.sin(ang)
        y = (t - 0.5) * height
        return (x, y, z)

    verts = []
    faces = []
    eps = 1e-4
    for i in range(tube_segments + 1):
        t = i / tube_segments
        cur = center(t)
        nxt = center(min(1.0, t + eps))
        tangent = normalize(sub(nxt, cur))
        helper = (0.0, 1.0, 0.0)
        if abs(tangent[1]) > 0.9:
            helper = (1.0, 0.0, 0.0)
        normal = normalize(cross(tangent, helper))
        binormal = normalize(cross(tangent, normal))
        for j in range(radial_segments):
            v = 2.0 * math.pi * j / radial_segments
            cx = math.cos(v) * tube_radius
            cy = math.sin(v) * tube_radius
            px = cur[0] + cx * normal[0] + cy * binormal[0]
            py = cur[1] + cx * normal[1] + cy * binormal[1]
            pz = cur[2] + cx * normal[2] + cy * binormal[2]
            verts.append((px, py, pz))

    for i in range(tube_segments):
        for j in range(radial_segments):
            a = i * radial_segments + j
            b = i * radial_segments + (j + 1) % radial_segments
            c = (i + 1) * radial_segments + j
            d = (i + 1) * radial_segments + (j + 1) % radial_segments
            faces.append((a, c, b))
            faces.append((b, c, d))

    normals = smooth_normals(verts, faces)
    return verts, normals, faces


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))

    v, n, f = gen_icosphere(subdiv=3, radius=1.0)
    write_obj(os.path.join(here, "icosphere.obj"), "icosphere", v, n, f)

    v, n, f = gen_torusknot()
    write_obj(os.path.join(here, "torusknot.obj"), "torusknot", v, n, f)

    v, n, f = gen_spring()
    write_obj(os.path.join(here, "spring.obj"), "spring", v, n, f)
