// Apps/UltraMail/engine/UltraMailSenderBrandTable.cpp
// The known-sender registry's data: the brands an inbox actually hears from,
// and - because the threat scan reasons about the same table - the brands
// phishing mail most often dresses up as: banks and brokers, payment services,
// crypto exchanges and wallets, online shops and marketplaces, parcel
// carriers, social networks, cloud, hosting and file-sharing services, domain
// registrars, tax and government agencies, telecoms, game stores and security
// software.
//
// Rules for an entry, because a wrong one is worse than a missing one:
//  * A domain goes in only when it is the brand's own. A domain here is
//    *trusted*: mail from it gets the brand's name, icon and the blue
//    "business contact" badge, so a guessed or lapsed domain would hand that
//    to whoever registers it.
//  * Country domains are listed one by one rather than through `labels`,
//    which would trust a squatted lidl.xyz as Lidl.
//  * A name that is also an ordinary word is NameClaim::KeywordsOnly, with
//    keywords specific enough not to occur in ordinary mail ("chase bank",
//    not "chase").
//  * No keyword may be a mailbox provider's name ("outlook", "gmail",
//    "icloud"): a display name that is just the sender's own address
//    ("jane@outlook.com") would then claim the brand.
//  * A brand whose real mail comes from hundreds of regional domains
//    (Sparkasse) is recognised but not claimed, so its genuine mail is not
//    flagged as impersonation.
//
// Version: 0.1.1 - Amazon, eBay, Google and DHL list their country domains
//                  instead of trusting their name under any suffix
// Version: 0.1.0 - split out of UltraMailSenderBrands.cpp; ~400 brands
// Author: UltraCanvas Framework / ULTRA OS
#include "UltraMailSenderBrandTable.h"

namespace UltraMail {

namespace {

using C = BrandCategory;
constexpr NameClaim KW = NameClaim::KeywordsOnly;

std::vector<BrandRule> BuildRules() {
    return {
        // ── Social networks ─────────────────────────────────────────────────
        { {"facebook",  "Facebook",  "https://www.facebook.com/favicon.ico",  0x1877F2, C::Social},
          {"facebook.com", "facebookmail.com", "fb.com", "meta.com", "messenger.com"}, {},
          {"facebook", "meta"} },
        { {"instagram", "Instagram", "https://www.instagram.com/favicon.ico", 0xE1306C, C::Social},
          {"instagram.com", "mail.instagram.com", "threads.net"}, {}, {"instagram"} },
        { {"whatsapp",  "WhatsApp",  "https://www.whatsapp.com/favicon.ico",  0x25D366, C::Messaging},
          {"whatsapp.com"}, {}, {"whatsapp"} },
        { {"linkedin",  "LinkedIn",  "https://www.linkedin.com/favicon.ico",  0x0A66C2, C::Social},
          {"linkedin.com"}, {}, {"linkedin"} },
        { {"x",         "X",         "https://abs.twimg.com/favicons/twitter.3.ico", 0x111111, C::Social},
          {"twitter.com", "x.com"}, {}, {"twitter"} },
        { {"claude",    "Claude",    "https://claude.ai/favicon.ico",         0xD97757, C::Technology},
          {"anthropic.com", "claude.ai", "claude.com"}, {}, {"anthropic", "claude"} },
        { {"openai",    "OpenAI",    "https://openai.com/favicon.ico",        0x10A37F, C::Technology},
          {"openai.com", "chatgpt.com"}, {}, {"openai", "chatgpt"} },
        { {"google",    "Google",    "https://www.google.com/favicon.ico",    0x4285F4, C::Technology},
          {"google.com", "googleapis.com", "googleusercontent.com", "google-analytics.com",
           "withgoogle.com", "firebase.com", "android.com",
           // Country sites, listed one by one: a label rule would also trust a
           // squatted google.xyz.
           "google.de", "google.at", "google.ch", "google.co.uk", "google.ie",
           "google.fr", "google.be", "google.nl", "google.it", "google.es",
           "google.pt", "google.pl", "google.cz", "google.se", "google.dk",
           "google.no", "google.fi", "google.com.tr", "google.ca", "google.com.mx",
           "google.com.br", "google.com.ar", "google.co.in", "google.co.jp",
           "google.co.kr", "google.com.hk", "google.com.sg", "google.com.au",
           "google.co.nz", "google.co.za"},
          {}, {"google"} },
        { {"youtube",   "YouTube",   "https://www.youtube.com/favicon.ico",   0xFF0000, C::Media},
          {"youtube.com", "youtu.be"}, {}, {"youtube"} },
        { {"apple",     "Apple",     "https://www.apple.com/favicon.ico",     0x555555, C::Technology},
          {"apple.com", "itunes.com", "apple.news"}, {},
          {"apple", "itunes", "appleid", "apple id"} },
        // "outlook" and "office" used to be keywords here: the first made
        // every "jane@outlook.com" display name claim Microsoft, the second
        // every office move.
        { {"microsoft", "Microsoft", "https://www.microsoft.com/favicon.ico", 0x0078D4, C::Technology},
          {"microsoft.com", "microsoftonline.com", "office.com", "office365.com",
           "sharepointonline.com", "azure.com", "windows.com", "skype.com",
           "xbox.com", "bing.com"}, {},
          {"microsoft", "onedrive", "sharepoint", "office 365", "microsoft 365",
           "outlook team", "xbox", "skype", "microsoft teams"} },
        { {"github",    "GitHub",    "https://github.com/favicon.ico",        0x24292F, C::Technology},
          {"github.com"}, {}, {"github"} },
        // "prime" alone was every "prime location" and "prime minister".
        { {"amazon",    "Amazon",    "https://www.amazon.com/favicon.ico",    0xFF9900, C::Shopping},
          {"amazon.com", "primevideo.com", "audible.com", "aws.amazon.com",
           "amazonaws.com", "aws.com",
           // The Amazon marketplaces.
           "amazon.ca", "amazon.com.mx", "amazon.com.br", "amazon.co.uk",
           "amazon.de", "amazon.fr", "amazon.it", "amazon.es", "amazon.nl",
           "amazon.com.be", "amazon.se", "amazon.pl", "amazon.com.tr", "amazon.ae",
           "amazon.sa", "amazon.eg", "amazon.in", "amazon.co.jp", "amazon.com.au",
           "amazon.sg", "amazon.cn"},
          {}, {"amazon", "amazon prime", "prime video", "aws"} },
        { {"paypal",    "PayPal",    "https://www.paypal.com/favicon.ico",    0x003087, C::Payment},
          {"paypal.com", "paypal-communication.com"}, {}, {"paypal"} },
        { {"stripe",    "Stripe",    "https://stripe.com/favicon.ico",        0x635BFF, C::Payment},
          {"stripe.com"}, {}, {"stripe"} },
        { {"ebay",      "eBay",      "https://www.ebay.com/favicon.ico",      0xE53238, C::Shopping},
          {"ebay.com", "ebay.co.uk", "ebay.ie", "ebay.de", "ebay.at", "ebay.ch",
           "ebay.fr", "ebay.be", "ebay.nl", "ebay.it", "ebay.es", "ebay.pl",
           "ebay.ca", "ebay.com.au", "ebay.com.hk", "ebay.com.sg", "ebay.com.my",
           "ebay.ph"},
          {}, {"ebay"} },
        // Dating services: favourite disguises of "you have a match" phishing.
        // ("Match" itself is claimed through "match.com" only - the word is
        // in every such subject.)
        { {"tinder",    "Tinder",    "https://tinder.com/favicon.ico",        0xFD5068, C::Social},
          {"tinder.com", "gotinder.com"}, {}, {"tinder"} },
        { {"bumble",    "Bumble",    "https://bumble.com/favicon.ico",        0xFFC629, C::Social},
          {"bumble.com", "team.bumble.com"}, {}, {"bumble"} },
        { {"hinge",     "Hinge",     "https://hinge.co/favicon.ico",          0x111111, C::Social},
          {"hinge.co"}, {}, {"hinge app"} },
        { {"okcupid",   "OkCupid",   "https://www.okcupid.com/favicon.ico",   0x0500BE, C::Social},
          {"okcupid.com"}, {}, {"okcupid"} },
        { {"parship",   "Parship",   "https://www.parship.com/favicon.ico",   0xC6004B, C::Social},
          {"parship.com", "parship.de"}, {}, {"parship"} },
        { {"match",     "Match",     "", 0x1F1F7A, C::Social},
          {"match.com"}, {}, {"match.com"}, KW },
        { {"grindr",    "Grindr",    "", 0xF5C300, C::Social},
          {"grindr.com"}, {}, {"grindr"} },
        { {"badoo",     "Badoo",     "", 0x783BF9, C::Social},
          {"badoo.com"}, {}, {"badoo"} },
        { {"pof",       "Plenty of Fish", "", 0x3B5998, C::Social},
          {"pof.com"}, {}, {"plenty of fish", "pof.com"} },
        { {"netflix",   "Netflix",   "https://www.netflix.com/favicon.ico",   0xE50914, C::Media},
          {"netflix.com"}, {}, {"netflix"} },
        { {"spotify",   "Spotify",   "https://www.spotify.com/favicon.ico",   0x1DB954, C::Media},
          {"spotify.com", "spotifymail.com"}, {}, {"spotify"} },
        { {"dropbox",   "Dropbox",   "https://www.dropbox.com/favicon.ico",   0x0061FF, C::CloudHosting},
          {"dropbox.com", "dropboxmail.com"}, {}, {"dropbox"} },
        { {"slack",     "Slack",     "https://slack.com/favicon.ico",         0x4A154B, C::Messaging},
          {"slack.com", "slack-mail.com"}, {}, {"slack"} },
        { {"discord",   "Discord",   "https://discord.com/assets/favicon.ico",0x5865F2, C::Messaging},
          {"discord.com", "discordapp.com"}, {}, {"discord"} },
        { {"telegram",  "Telegram",  "https://telegram.org/favicon.ico",      0x26A5E4, C::Messaging},
          {"telegram.org"}, {}, {"telegram"} },
        { {"reddit",    "Reddit",    "https://www.reddit.com/favicon.ico",    0xFF4500, C::Social},
          {"reddit.com", "redditmail.com"}, {}, {"reddit"} },
        { {"tiktok",    "TikTok",    "https://www.tiktok.com/favicon.ico",    0x111111, C::Social},
          {"tiktok.com"}, {}, {"tiktok"} },
        { {"zoom",      "Zoom",      "https://zoom.us/favicon.ico",           0x2D8CFF, C::Technology},
          {"zoom.us"}, {}, {"zoom"} },
        // "Booking" alone was every hotel's "your booking is confirmed".
        { {"booking",   "Booking.com", "https://www.booking.com/favicon.ico", 0x003580, C::Travel},
          {"booking.com"}, {}, {"booking.com"} },
        { {"airbnb",    "Airbnb",    "https://www.airbnb.com/favicon.ico",    0xFF5A5F, C::Travel},
          {"airbnb.com"}, {}, {"airbnb"} },
        { {"dhl",       "DHL",       "https://www.dhl.com/favicon.ico",       0xD40511, C::Delivery},
          {"dhl.com", "dhl.de", "dhl.at", "dhl.ch", "dhl.co.uk", "dhl.fr", "dhl.be",
           "dhl.nl", "dhl.it", "dhl.es", "dhl.pl"},
          {}, {"dhl"} },
        // "ups" alone was every "follow-ups" and "ups and downs".
        { {"ups",       "UPS",       "https://www.ups.com/favicon.ico",       0x351C15, C::Delivery},
          {"ups.com"}, {}, {"ups.com", "ups my choice", "united parcel service"}, KW },
        { {"fedex",     "FedEx",     "https://www.fedex.com/favicon.ico",     0x4D148C, C::Delivery},
          {"fedex.com"}, {}, {"fedex"} },

        // ── Crowdfunding and creator support ────────────────────────────────
        // A backed project or a supported creator is a business relationship
        // the user keeps: these are among the entries most worth collecting
        // into the address book (see ContactCollector::CollectSender).
        { {"kickstarter", "Kickstarter", "https://www.kickstarter.com/favicon.ico", 0x05CE78, C::Crowdfunding},
          {"kickstarter.com"}, {}, {"kickstarter"} },
        { {"indiegogo", "Indiegogo", "https://www.indiegogo.com/favicon.ico", 0xEB1478, C::Crowdfunding},
          {"indiegogo.com"}, {}, {"indiegogo"} },
        { {"gofundme", "GoFundMe", "https://www.gofundme.com/favicon.ico", 0x02A95C, C::Crowdfunding},
          {"gofundme.com"}, {}, {"gofundme"} },
        { {"startnext", "Startnext", "https://www.startnext.com/favicon.ico", 0x27ADE3, C::Crowdfunding},
          {"startnext.com", "startnext.de"}, {}, {"startnext"} },
        { {"crowdsupply", "Crowd Supply", "https://www.crowdsupply.com/favicon.ico", 0x1B4E6B, C::Crowdfunding},
          {"crowdsupply.com"}, {}, {"crowd supply", "crowdsupply"} },
        { {"patreon", "Patreon", "https://www.patreon.com/favicon.ico", 0xFF424D, C::CreatorSupport},
          {"patreon.com"}, {}, {"patreon"} },
        { {"buymeacoffee", "Buy Me a Coffee", "https://buymeacoffee.com/favicon.ico", 0xFFDD00, C::CreatorSupport},
          {"buymeacoffee.com"}, {}, {"buy me a coffee", "buymeacoffee"} },
        { {"kofi", "Ko-fi", "https://ko-fi.com/favicon.ico", 0xFF5E5B, C::CreatorSupport},
          {"ko-fi.com"}, {}, {"ko-fi", "kofi"} },
        { {"liberapay", "Liberapay", "https://liberapay.com/favicon.ico", 0xF6C915, C::CreatorSupport},
          {"liberapay.com"}, {}, {"liberapay"} },
        { {"opencollective", "Open Collective", "https://opencollective.com/favicon.ico", 0x3385FF, C::CreatorSupport},
          {"opencollective.com"}, {}, {"open collective", "opencollective"} },
        { {"gumroad", "Gumroad", "https://gumroad.com/favicon.ico", 0xFF90E8, C::CreatorSupport},
          {"gumroad.com"}, {}, {"gumroad"} },
        { {"substack", "Substack", "https://substack.com/favicon.ico", 0xFF6719, C::CreatorSupport},
          {"substack.com"}, {}, {"substack"} },

        // ── More social networks and messengers ─────────────────────────────
        { {"pinterest", "Pinterest", "https://www.pinterest.com/favicon.ico", 0xE60023, C::Social},
          {"pinterest.com", "pinterestmail.com"}, {"pinterest"}, {"pinterest"} },
        { {"tumblr", "Tumblr", "https://www.tumblr.com/favicon.ico", 0x36465D, C::Social},
          {"tumblr.com", "tumblr.net"}, {}, {"tumblr"} },
        { {"mastodon", "Mastodon", "https://joinmastodon.org/favicon.ico", 0x6364FF, C::Social},
          {"joinmastodon.org", "mastodon.social"}, {}, {"mastodon"} },
        { {"twitch", "Twitch", "https://www.twitch.tv/favicon.ico", 0x9146FF, C::Media},
          {"twitch.tv"}, {}, {"twitch"} },
        { {"vimeo", "Vimeo", "https://vimeo.com/favicon.ico", 0x1AB7EA, C::Media},
          {"vimeo.com"}, {}, {"vimeo"} },
        { {"etsy", "Etsy", "https://www.etsy.com/favicon.ico", 0xF1641E, C::Shopping},
          {}, {"etsy"}, {"etsy"} },
        { {"snapchat",  "Snapchat",  "", 0xFFFC00, C::Social},
          {"snapchat.com", "snap.com"}, {}, {"snapchat"} },
        { {"bluesky",   "Bluesky",   "", 0x1185FE, C::Social},
          {"bsky.app"}, {}, {"bluesky"} },
        { {"quora",     "Quora",     "", 0xB92B27, C::Social},
          {"quora.com"}, {}, {"quora"} },
        { {"nextdoor",  "Nextdoor",  "", 0x8ED500, C::Social},
          {"nextdoor.com"}, {}, {"nextdoor"} },
        { {"xing",      "XING",      "", 0x006567, C::Social},
          {"xing.com"}, {}, {"xing"} },
        { {"meetup",    "Meetup",    "", 0xF65858, C::Social},
          {"meetup.com"}, {}, {"meetup.com"}, KW },
        { {"wechat",    "WeChat",    "", 0x07C160, C::Messaging},
          {"wechat.com"}, {}, {"wechat"} },
        { {"signal",    "Signal",    "", 0x3A76F0, C::Messaging},
          {"signal.org"}, {}, {"signal messenger", "signal.org"}, KW },
        { {"viber",     "Viber",     "", 0x7360F2, C::Messaging},
          {"viber.com"}, {}, {"viber"} },

        // ── Banks and brokers: North America ────────────────────────────────
        { {"chase",     "Chase",     "", 0x117ACA, C::Banking},
          {"chase.com", "jpmorgan.com", "jpmorganchase.com"}, {},
          {"chase bank", "jpmorgan", "jp morgan", "chase.com"}, KW },
        { {"bankofamerica", "Bank of America", "", 0xE31837, C::Banking},
          {"bankofamerica.com", "ml.com"}, {}, {"bankofamerica", "merrill lynch"} },
        { {"wellsfargo", "Wells Fargo", "", 0xD71E28, C::Banking},
          {"wellsfargo.com", "wellsfargoadvisors.com"}, {}, {"wellsfargo"} },
        { {"citi",      "Citi",      "", 0x056DAE, C::Banking},
          {"citi.com", "citibank.com", "citigroup.com"}, {}, {"citibank"} },
        { {"capitalone", "Capital One", "", 0x004977, C::Banking},
          {"capitalone.com"}, {}, {"capitalone"} },
        { {"usbank",    "U.S. Bank", "", 0x0C2074, C::Banking},
          {"usbank.com"}, {}, {"usbank", "us bank"} },
        { {"pnc",       "PNC",       "", 0xEF7622, C::Banking},
          {"pnc.com"}, {}, {"pnc bank"} },
        { {"truist",    "Truist",    "", 0x2E1A47, C::Banking},
          {"truist.com"}, {}, {"truist"} },
        { {"td",        "TD Bank",   "", 0x34A853, C::Banking},
          {"td.com", "tdbank.com"}, {}, {"td bank", "td canada trust"} },
        { {"amex",      "American Express", "", 0x006FCF, C::Banking},
          {"americanexpress.com", "aexp.com"}, {}, {"amex", "americanexpress"} },
        { {"discover",  "Discover",  "", 0xFF6000, C::Banking},
          {"discover.com"}, {}, {"discover card", "discover bank"}, KW },
        { {"ally",      "Ally",      "", 0x8A3575, C::Banking},
          {"ally.com"}, {}, {"ally bank", "ally financial"}, KW },
        { {"navyfederal", "Navy Federal Credit Union", "", 0x003C71, C::Banking},
          {"navyfederal.org"}, {}, {"navy federal"} },
        { {"usaa",      "USAA",      "", 0x12395B, C::Banking},
          {"usaa.com"}, {}, {"usaa"} },
        { {"schwab",    "Charles Schwab", "", 0x00A0DF, C::Banking},
          {"schwab.com"}, {}, {"schwab"} },
        { {"fidelity",  "Fidelity",  "", 0x368727, C::Banking},
          {"fidelity.com"}, {}, {"fidelity investments"}, KW },
        { {"vanguard",  "Vanguard",  "", 0x96151D, C::Banking},
          {"vanguard.com"}, {}, {"vanguard investments", "vanguard group"}, KW },
        { {"robinhood", "Robinhood", "", 0x00C805, C::Banking},
          {"robinhood.com"}, {}, {"robinhood"} },
        { {"rbc",       "RBC Royal Bank", "", 0x005DAA, C::Banking},
          {"rbc.com", "rbcroyalbank.com"}, {}, {"rbc", "royal bank of canada"} },
        { {"scotiabank", "Scotiabank", "", 0xEC111A, C::Banking},
          {"scotiabank.com"}, {}, {"scotiabank"} },
        { {"bmo",       "BMO",       "", 0x0079C1, C::Banking},
          {"bmo.com"}, {}, {"bank of montreal"} },
        { {"cibc",      "CIBC",      "", 0xC41F3E, C::Banking},
          {"cibc.com"}, {}, {"cibc"} },

        // ── Banks and brokers: UK and Ireland ───────────────────────────────
        { {"barclays",  "Barclays",  "", 0x00AEEF, C::Banking},
          {"barclays.co.uk", "barclays.com", "barclaycard.co.uk"}, {}, {"barclaycard"} },
        { {"hsbc",      "HSBC",      "", 0xDB0011, C::Banking},
          {"hsbc.com", "hsbc.co.uk", "hsbc.com.hk"}, {}, {"hsbc"} },
        { {"lloyds",    "Lloyds Bank", "", 0x006A4D, C::Banking},
          {"lloydsbank.com", "lloydsbank.co.uk"}, {}, {"lloyds", "lloydsbank"} },
        { {"natwest",   "NatWest",   "", 0x5A287D, C::Banking},
          {"natwest.com"}, {}, {"natwest"} },
        { {"rbs",       "RBS",       "", 0x002D62, C::Banking},
          {"rbs.co.uk"}, {}, {"royal bank of scotland"} },
        { {"tsb",       "TSB",       "", 0x004A9C, C::Banking},
          {"tsb.co.uk"}, {}, {"tsb bank"} },
        { {"halifax",   "Halifax",   "", 0x005EB8, C::Banking},
          {"halifax.co.uk"}, {}, {"halifax bank", "halifax online banking"}, KW },
        { {"nationwide", "Nationwide", "", 0x1C1F5E, C::Banking},
          {"nationwide.co.uk"}, {}, {"nationwide building society"}, KW },
        { {"santander", "Santander", "", 0xEC0000, C::Banking},
          {"santander.co.uk", "santander.com", "santander.de", "santanderbank.com",
           "bancosantander.es"}, {}, {"santander"} },
        { {"monzo",     "Monzo",     "", 0xFF4F40, C::Banking},
          {"monzo.com"}, {}, {"monzo"} },
        { {"revolut",   "Revolut",   "", 0x0075EB, C::Banking},
          {"revolut.com"}, {}, {"revolut"} },
        { {"starling",  "Starling Bank", "", 0x6935D3, C::Banking},
          {"starlingbank.com"}, {}, {"starling bank", "starlingbank"}, KW },
        { {"metrobank", "Metro Bank", "", 0xD52B1E, C::Banking},
          {"metrobankonline.co.uk"}, {}, {"metro bank"} },

        // ── Banks and brokers: Germany, Austria, Switzerland ────────────────
        { {"deutschebank", "Deutsche Bank", "", 0x0018A8, C::Banking},
          {"deutsche-bank.de", "db.com"}, {}, {"deutsche bank"} },
        { {"commerzbank", "Commerzbank", "", 0xFFD700, C::Banking},
          {"commerzbank.de", "commerzbank.com"}, {}, {"commerzbank"} },
        // Recognised, not claimed: most Sparkassen mail from their own
        // regional domain (sparkasse-<region>.de, ksk-<county>.de), so a claim
        // of "Sparkasse" from one of those would read as impersonation.
        { {"sparkasse", "Sparkasse", "", 0xFF0000, C::Banking},
          {"sparkasse.de", "sparkasse.at"}, {}, {}, KW },
        { {"ing",       "ING",       "", 0xFF6200, C::Banking},
          {"ing.de", "ing.com", "ing.nl", "ing.be"}, {}, {"ing-diba", "ing diba", "ing bank"}, KW },
        { {"dkb",       "DKB",       "", 0x148DEA, C::Banking},
          {"dkb.de"}, {}, {"deutsche kreditbank"} },
        { {"comdirect", "comdirect", "", 0xFFF500, C::Banking},
          {"comdirect.de"}, {}, {"comdirect"} },
        { {"postbank",  "Postbank",  "", 0xFFCC00, C::Banking},
          {"postbank.de"}, {}, {"postbank"} },
        { {"n26",       "N26",       "", 0x36A18B, C::Banking},
          {"n26.com"}, {}, {"n26"} },
        { {"consorsbank", "Consorsbank", "", 0x0050A0, C::Banking},
          {"consorsbank.de"}, {}, {"consorsbank"} },
        { {"hypovereinsbank", "HypoVereinsbank", "", 0xE2001A, C::Banking},
          {"hypovereinsbank.de"}, {}, {"hypovereinsbank"} },
        { {"targobank", "Targobank", "", 0x002D5F, C::Banking},
          {"targobank.de"}, {}, {"targobank"} },
        { {"traderepublic", "Trade Republic", "", 0x111111, C::Banking},
          {"traderepublic.com"}, {}, {"trade republic", "traderepublic"} },
        { {"scalable",  "Scalable Capital", "", 0x2E2E2E, C::Banking},
          {"scalable.capital"}, {}, {"scalable capital"} },
        { {"ubs",       "UBS",       "", 0xE60000, C::Banking},
          {"ubs.com"}, {}, {"ubs"} },
        { {"postfinance", "PostFinance", "", 0xFFCC00, C::Banking},
          {"postfinance.ch"}, {}, {"postfinance"} },

        // ── Banks and brokers: rest of Europe ───────────────────────────────
        { {"abnamro",   "ABN AMRO",  "", 0x00857A, C::Banking},
          {"abnamro.nl", "abnamro.com"}, {}, {"abnamro"} },
        { {"rabobank",  "Rabobank",  "", 0x000099, C::Banking},
          {"rabobank.nl", "rabobank.com"}, {}, {"rabobank"} },
        { {"bunq",      "bunq",      "", 0x2F9D5F, C::Banking},
          {"bunq.com"}, {}, {"bunq"} },
        { {"bnpparibas", "BNP Paribas", "", 0x00915A, C::Banking},
          {"bnpparibas.com", "mabanque.bnpparibas"}, {}, {"bnp paribas", "bnpparibas"} },
        { {"societegenerale", "Société Générale", "", 0xE9041E, C::Banking},
          {"societegenerale.fr", "societegenerale.com"}, {}, {"societe generale"} },
        { {"creditagricole", "Crédit Agricole", "", 0x007D8F, C::Banking},
          {"credit-agricole.fr", "credit-agricole.com"}, {}, {"credit agricole"} },
        { {"labanquepostale", "La Banque Postale", "", 0x003DA5, C::Banking},
          {"labanquepostale.fr"}, {}, {"banque postale"} },
        { {"boursobank", "BoursoBank", "", 0xD3005C, C::Banking},
          {"boursobank.com", "boursorama.com"}, {}, {"boursorama"} },
        { {"bbva",      "BBVA",      "", 0x004481, C::Banking},
          {"bbva.es", "bbva.com"}, {}, {"bbva"} },
        { {"caixabank", "CaixaBank", "", 0x007EAE, C::Banking},
          {"caixabank.es", "caixabank.com"}, {}, {"caixabank"} },
        { {"intesasanpaolo", "Intesa Sanpaolo", "", 0x006837, C::Banking},
          {"intesasanpaolo.com"}, {}, {"intesa sanpaolo"} },
        { {"unicredit", "UniCredit", "", 0xE2001A, C::Banking},
          {"unicredit.it", "unicreditgroup.eu"}, {}, {"unicredit"} },
        { {"nordea",    "Nordea",    "", 0x0000A0, C::Banking},
          {"nordea.com", "nordea.fi", "nordea.se", "nordea.dk", "nordea.no"}, {}, {"nordea"} },
        { {"danskebank", "Danske Bank", "", 0x003755, C::Banking},
          {"danskebank.com", "danskebank.dk"}, {}, {"danske bank"} },
        { {"swedbank",  "Swedbank",  "", 0xFF5F00, C::Banking},
          {"swedbank.se", "swedbank.com"}, {}, {"swedbank"} },
        { {"handelsbanken", "Handelsbanken", "", 0x005AA0, C::Banking},
          {"handelsbanken.se", "handelsbanken.com"}, {}, {"handelsbanken"} },
        { {"dnb",       "DNB",       "", 0x007272, C::Banking},
          {"dnb.no"}, {}, {"dnb bank"} },
        { {"etoro",     "eToro",     "", 0x13C636, C::Banking},
          {"etoro.com"}, {}, {"etoro"} },

        // ── Banks: Asia-Pacific and Latin America ───────────────────────────
        { {"commbank",  "Commonwealth Bank", "", 0xFFCC00, C::Banking},
          {"commbank.com.au", "cba.com.au"}, {}, {"commbank"} },
        { {"westpac",   "Westpac",   "", 0xDA1710, C::Banking},
          {"westpac.com.au"}, {}, {"westpac"} },
        { {"anz",       "ANZ",       "", 0x007DBA, C::Banking},
          {"anz.com", "anz.com.au", "anz.co.nz"}, {}, {"anz bank"} },
        { {"nab",       "NAB",       "", 0xC20000, C::Banking},
          {"nab.com.au"}, {}, {"national australia bank"} },
        { {"sbi",       "State Bank of India", "", 0x2D7BBF, C::Banking},
          {"sbi.co.in", "onlinesbi.sbi"}, {}, {"onlinesbi", "sbi bank"} },
        { {"hdfcbank",  "HDFC Bank", "", 0x004C8F, C::Banking},
          {"hdfcbank.com"}, {}, {"hdfc"} },
        { {"icicibank", "ICICI Bank", "", 0xB02A30, C::Banking},
          {"icicibank.com"}, {}, {"icici"} },
        { {"dbs",       "DBS",       "", 0xFF3333, C::Banking},
          {"dbs.com", "dbs.com.sg"}, {}, {"dbs bank", "posb"} },
        { {"ocbc",      "OCBC",      "", 0xE3241B, C::Banking},
          {"ocbc.com"}, {}, {"ocbc"} },
        { {"itau",      "Itaú",      "", 0xEC7000, C::Banking},
          {"itau.com.br"}, {}, {"itau"} },
        { {"nubank",    "Nubank",    "", 0x820AD1, C::Banking},
          {"nubank.com.br"}, {}, {"nubank"} },
        { {"bradesco",  "Bradesco",  "", 0xCC092F, C::Banking},
          {"bradesco.com.br"}, {}, {"bradesco"} },
        { {"bancodobrasil", "Banco do Brasil", "", 0xFAE128, C::Banking},
          {"bb.com.br"}, {}, {"banco do brasil"} },

        // ── Payment services and cards ──────────────────────────────────────
        { {"venmo",     "Venmo",     "", 0x008CFF, C::Payment},
          {"venmo.com"}, {}, {"venmo"} },
        { {"zelle",     "Zelle",     "", 0x6D1ED4, C::Payment},
          {"zellepay.com"}, {}, {"zelle"} },
        { {"cashapp",   "Cash App",  "https://cash.app/favicon.ico", 0x00D632, C::Payment},
          {"cash.app"}, {}, {"cashapp"} },
        { {"square",    "Square",    "", 0x3E4348, C::Payment},
          {"squareup.com"}, {}, {"squareup"}, KW },
        { {"wise",      "Wise",      "", 0x9FE870, C::Payment},
          {"wise.com", "transferwise.com"}, {}, {"transferwise", "wise.com"}, KW },
        { {"westernunion", "Western Union", "", 0xFFDD00, C::Payment},
          {"westernunion.com"}, {}, {"westernunion"} },
        { {"moneygram", "MoneyGram", "", 0xDA291C, C::Payment},
          {"moneygram.com"}, {}, {"moneygram"} },
        { {"remitly",   "Remitly",   "", 0x1A4CA1, C::Payment},
          {"remitly.com"}, {}, {"remitly"} },
        { {"xoom",      "Xoom",      "", 0x0F7EB4, C::Payment},
          {"xoom.com"}, {}, {"xoom"} },
        { {"payoneer",  "Payoneer",  "", 0xFF4800, C::Payment},
          {"payoneer.com"}, {}, {"payoneer"} },
        { {"skrill",    "Skrill",    "", 0x862165, C::Payment},
          {"skrill.com"}, {}, {"skrill"} },
        { {"neteller",  "Neteller",  "", 0x83BA3B, C::Payment},
          {"neteller.com"}, {}, {"neteller"} },
        { {"paysafecard", "paysafecard", "", 0x008AC9, C::Payment},
          {"paysafecard.com"}, {}, {"paysafecard"} },
        { {"klarna",    "Klarna",    "", 0xFFB3C7, C::Payment},
          {"klarna.com"}, {}, {"klarna"} },
        { {"afterpay",  "Afterpay",  "", 0xB2FCE4, C::Payment},
          {"afterpay.com"}, {}, {"afterpay"} },
        { {"affirm",    "Affirm",    "", 0x4A4AF4, C::Payment},
          {"affirm.com"}, {}, {"affirm.com"}, KW },
        { {"adyen",     "Adyen",     "", 0x0ABF53, C::Payment},
          {"adyen.com"}, {}, {"adyen"} },
        { {"visa",      "Visa",      "", 0x1A1F71, C::Payment},
          {"visa.com"}, {}, {"visa card", "verified by visa", "visa secure"}, KW },
        { {"mastercard", "Mastercard", "", 0xEB001B, C::Payment},
          {"mastercard.com"}, {}, {"mastercard"} },
        { {"interac",   "Interac",   "", 0xFDB813, C::Payment},
          {"interac.ca"}, {}, {"interac", "e-transfer"} },
        { {"twint",     "TWINT",     "", 0x000000, C::Payment},
          {"twint.ch"}, {}, {"twint"} },
        { {"alipay",    "Alipay",    "", 0x1677FF, C::Payment},
          {"alipay.com"}, {}, {"alipay"} },
        { {"paytm",     "Paytm",     "", 0x00BAF2, C::Payment},
          {"paytm.com"}, {}, {"paytm"} },
        { {"phonepe",   "PhonePe",   "", 0x5F259F, C::Payment},
          {"phonepe.com"}, {}, {"phonepe"} },

        // ── Crypto exchanges and wallets ────────────────────────────────────
        // The coin names themselves ("bitcoin", "ethereum") are deliberately
        // not keywords: they name no company.
        { {"coinbase",  "Coinbase",  "", 0x0052FF, C::Crypto},
          {"coinbase.com"}, {}, {"coinbase"} },
        { {"binance",   "Binance",   "", 0xF0B90B, C::Crypto},
          {"binance.com", "binance.us"}, {}, {"binance"} },
        { {"kraken",    "Kraken",    "", 0x5741D9, C::Crypto},
          {"kraken.com"}, {}, {"kraken"} },
        { {"cryptocom", "Crypto.com", "", 0x002D74, C::Crypto},
          {"crypto.com"}, {}, {"crypto.com"} },
        // "Gemini" is also Google's assistant and a star sign.
        { {"gemini",    "Gemini",    "", 0x00DCFA, C::Crypto},
          {"gemini.com"}, {}, {"gemini exchange", "gemini.com"}, KW },
        { {"bitstamp",  "Bitstamp",  "", 0x30B34B, C::Crypto},
          {"bitstamp.net"}, {}, {"bitstamp"} },
        { {"bitfinex",  "Bitfinex",  "", 0x16B157, C::Crypto},
          {"bitfinex.com"}, {}, {"bitfinex"} },
        { {"kucoin",    "KuCoin",    "", 0x24AE8F, C::Crypto},
          {"kucoin.com"}, {}, {"kucoin"} },
        { {"okx",       "OKX",       "", 0x111111, C::Crypto},
          {"okx.com"}, {}, {"okx"} },
        { {"bybit",     "Bybit",     "", 0xF7A600, C::Crypto},
          {"bybit.com"}, {}, {"bybit"} },
        { {"bitget",    "Bitget",    "", 0x00F0FF, C::Crypto},
          {"bitget.com"}, {}, {"bitget"} },
        { {"gateio",    "Gate.io",   "", 0x2354E6, C::Crypto},
          {"gate.io"}, {}, {"gate.io"} },
        { {"bitpanda",  "Bitpanda",  "", 0x2B9A66, C::Crypto},
          {"bitpanda.com"}, {}, {"bitpanda"} },
        { {"bitvavo",   "Bitvavo",   "", 0x0051FF, C::Crypto},
          {"bitvavo.com"}, {}, {"bitvavo"} },
        { {"bitcoinde", "Bitcoin.de", "", 0xF7931A, C::Crypto},
          {"bitcoin.de"}, {}, {"bitcoin.de"} },
        { {"nexo",      "Nexo",      "", 0x1A4199, C::Crypto},
          {"nexo.com"}, {}, {"nexo"} },
        { {"uphold",    "Uphold",    "", 0x49CC68, C::Crypto},
          {"uphold.com"}, {}, {"uphold.com"}, KW },
        { {"blockchaincom", "Blockchain.com", "", 0x121D33, C::Crypto},
          {"blockchain.com"}, {}, {"blockchain.com"} },
        { {"metamask",  "MetaMask",  "", 0xF6851B, C::Crypto},
          {"metamask.io"}, {}, {"metamask"} },
        { {"ledger",    "Ledger",    "", 0x111111, C::Crypto},
          {"ledger.com"}, {}, {"ledger live", "ledger wallet", "ledger nano"}, KW },
        { {"trezor",    "Trezor",    "", 0x00854D, C::Crypto},
          {"trezor.io"}, {}, {"trezor"} },
        { {"trustwallet", "Trust Wallet", "", 0x3375BB, C::Crypto},
          {"trustwallet.com"}, {}, {"trust wallet", "trustwallet"} },
        { {"exodus",    "Exodus",    "", 0x1F2033, C::Crypto},
          {"exodus.com"}, {}, {"exodus wallet"}, KW },
        { {"phantom",   "Phantom",   "https://phantom.app/favicon.ico", 0xAB9FF2, C::Crypto},
          {"phantom.app"}, {}, {"phantom wallet"}, KW },
        { {"opensea",   "OpenSea",   "", 0x2081E2, C::Crypto},
          {"opensea.io"}, {}, {"opensea"} },
        { {"uniswap",   "Uniswap",   "", 0xFF007A, C::Crypto},
          {"uniswap.org"}, {}, {"uniswap"} },

        // ── Online shops, marketplaces, food delivery ───────────────────────
        { {"walmart",   "Walmart",   "", 0x0071CE, C::Shopping},
          {"walmart.com", "walmart.ca"}, {}, {"walmart"} },
        { {"target",    "Target",    "", 0xCC0000, C::Shopping},
          {"target.com"}, {}, {"target.com", "target circle"}, KW },
        { {"bestbuy",   "Best Buy",  "", 0x0046BE, C::Shopping},
          {"bestbuy.com", "bestbuy.ca", "geeksquad.com"}, {}, {"bestbuy", "geek squad"} },
        { {"costco",    "Costco",    "", 0xE31837, C::Shopping},
          {"costco.com", "costco.ca", "costco.co.uk"}, {}, {"costco"} },
        { {"homedepot", "The Home Depot", "", 0xF96302, C::Shopping},
          {"homedepot.com"}, {}, {"home depot", "homedepot"} },
        { {"lowes",     "Lowe's",    "", 0x004990, C::Shopping},
          {"lowes.com"}, {}, {"lowes"} },
        { {"macys",     "Macy's",    "", 0xE21A2C, C::Shopping},
          {"macys.com"}, {}, {"macys"} },
        { {"wayfair",   "Wayfair",   "", 0x7F187F, C::Shopping},
          {"wayfair.com"}, {}, {"wayfair"} },
        { {"newegg",    "Newegg",    "", 0xF7A21B, C::Shopping},
          {"newegg.com"}, {}, {"newegg"} },
        { {"aliexpress", "AliExpress", "", 0xE62E04, C::Shopping},
          {"aliexpress.com", "aliexpress.us"}, {}, {"aliexpress"} },
        { {"alibaba",   "Alibaba",   "", 0xFF6A00, C::Shopping},
          {"alibaba.com"}, {}, {"alibaba"} },
        { {"temu",      "Temu",      "", 0xFB7701, C::Shopping},
          {"temu.com"}, {}, {"temu"} },
        { {"shein",     "SHEIN",     "", 0x111111, C::Shopping},
          {"shein.com"}, {}, {"shein"} },
        { {"wish",      "Wish",      "", 0x2FB7EC, C::Shopping},
          {"wish.com"}, {}, {"wish.com"}, KW },
        { {"shopify",   "Shopify",   "", 0x95BF47, C::Shopping},
          {"shopify.com"}, {}, {"shopify"} },
        { {"rakuten",   "Rakuten",   "", 0xBF0000, C::Shopping},
          {"rakuten.com", "rakuten.co.jp"}, {}, {"rakuten"} },
        { {"mercadolibre", "Mercado Libre", "", 0xFFE600, C::Shopping},
          {"mercadolibre.com", "mercadolibre.com.mx", "mercadolibre.com.ar",
           "mercadolivre.com.br"}, {}, {"mercadolibre", "mercado livre", "mercadolivre"} },
        { {"flipkart",  "Flipkart",  "", 0x2874F0, C::Shopping},
          {"flipkart.com"}, {}, {"flipkart"} },
        { {"ikea",      "IKEA",      "", 0x0058A3, C::Shopping},
          {"ikea.com"}, {}, {"ikea"} },
        { {"zalando",   "Zalando",   "", 0xFF6900, C::Shopping},
          {"zalando.com", "zalando.de", "zalando.at", "zalando.ch", "zalando.co.uk",
           "zalando.fr", "zalando.it", "zalando.es", "zalando.nl", "zalando.be",
           "zalando.pl"}, {}, {"zalando"} },
        { {"otto",      "OTTO",      "", 0xF00020, C::Shopping},
          {"otto.de"}, {}, {"otto.de"}, KW },
        { {"asos",      "ASOS",      "", 0x2D2D2D, C::Shopping},
          {"asos.com"}, {}, {"asos"} },
        { {"vinted",    "Vinted",    "", 0x09B1BA, C::Shopping},
          {"vinted.com", "vinted.de", "vinted.fr", "vinted.co.uk", "vinted.it",
           "vinted.es", "vinted.nl", "vinted.pl", "vinted.at", "vinted.be"}, {}, {"vinted"} },
        { {"kleinanzeigen", "Kleinanzeigen", "", 0x86B817, C::Shopping},
          {"kleinanzeigen.de"}, {}, {"kleinanzeigen"} },
        { {"marktplaats", "Marktplaats", "", 0xEDA566, C::Shopping},
          {"marktplaats.nl"}, {}, {"marktplaats"} },
        { {"leboncoin", "leboncoin", "", 0xEC5A13, C::Shopping},
          {"leboncoin.fr"}, {}, {"leboncoin"} },
        { {"allegro",   "Allegro",   "", 0xFF5A00, C::Shopping},
          {"allegro.pl"}, {}, {"allegro.pl"}, KW },
        { {"craigslist", "craigslist", "", 0x5A0EA0, C::Shopping},
          {"craigslist.org"}, {}, {"craigslist"} },
        { {"mediamarkt", "MediaMarkt", "", 0xDF0000, C::Shopping},
          {"mediamarkt.de", "mediamarkt.at", "mediamarkt.ch", "mediamarkt.nl",
           "mediamarkt.es", "mediamarkt.com"}, {}, {"mediamarkt", "media markt"} },
        { {"lidl",      "Lidl",      "", 0x0050AA, C::Shopping},
          {"lidl.com", "lidl.de", "lidl.at", "lidl.ch", "lidl.co.uk", "lidl.fr",
           "lidl.it", "lidl.es", "lidl.nl", "lidl.be", "lidl.pl"}, {}, {"lidl"} },
        { {"aldi",      "Aldi",      "", 0x00005F, C::Shopping},
          {"aldi.com", "aldi-sued.de", "aldi-nord.de", "aldi.co.uk", "aldi.us"}, {},
          {"aldi", "aldi sued", "aldi nord"} },
        { {"tesco",     "Tesco",     "", 0x00539F, C::Shopping},
          {"tesco.com"}, {}, {"tesco"} },
        { {"sainsburys", "Sainsbury's", "", 0xF06C00, C::Shopping},
          {"sainsburys.co.uk"}, {}, {"sainsburys"} },
        { {"argos",     "Argos",     "", 0xD42114, C::Shopping},
          {"argos.co.uk"}, {}, {"argos"} },
        { {"groupon",   "Groupon",   "", 0x53A318, C::Shopping},
          {"groupon.com"}, {}, {"groupon"} },
        { {"instacart", "Instacart", "", 0x43B02A, C::Shopping},
          {"instacart.com"}, {}, {"instacart"} },
        { {"doordash",  "DoorDash",  "", 0xFF3008, C::Shopping},
          {"doordash.com"}, {}, {"doordash"} },
        { {"deliveroo", "Deliveroo", "", 0x00CCBC, C::Shopping},
          {"deliveroo.com", "deliveroo.co.uk"}, {}, {"deliveroo"} },
        { {"lieferando", "Lieferando", "", 0xFF8000, C::Shopping},
          {"lieferando.de"}, {}, {"lieferando"} },

        // ── Parcel carriers and postal services ─────────────────────────────
        { {"usps",      "USPS",      "", 0x333366, C::Delivery},
          {"usps.com"}, {}, {"usps", "united states postal service"} },
        { {"royalmail", "Royal Mail", "", 0xDA202A, C::Delivery},
          {"royalmail.com"}, {}, {"royal mail", "royalmail"} },
        { {"parcelforce", "Parcelforce", "", 0xE41F2D, C::Delivery},
          {"parcelforce.com"}, {}, {"parcelforce"} },
        { {"evri",      "Evri",      "", 0x007BC4, C::Delivery},
          {"evri.com", "myhermes.de", "hermesworld.com"}, {}, {"evri", "hermes"} },
        { {"yodel",     "Yodel",     "", 0x81BC00, C::Delivery},
          {"yodel.co.uk"}, {}, {"yodel"} },
        { {"dpd",       "DPD",       "", 0xDC0032, C::Delivery},
          {"dpd.com", "dpd.de", "dpd.co.uk", "dpd.at", "dpd.fr", "dpd.nl", "dpd.be"}, {}, {"dpd"} },
        { {"gls",       "GLS",       "", 0x061AB1, C::Delivery},
          {"gls-group.eu", "gls-group.com", "gls-pakete.de"}, {}, {"gls"} },
        { {"deutschepost", "Deutsche Post", "", 0xFFCC00, C::Delivery},
          {"deutschepost.de", "deutschepost.com"}, {}, {"deutsche post"} },
        { {"tnt",       "TNT",       "", 0xFF6600, C::Delivery},
          {"tnt.com"}, {}, {"tnt express"} },
        { {"aramex",    "Aramex",    "", 0xE2231A, C::Delivery},
          {"aramex.com"}, {}, {"aramex"} },
        { {"inpost",    "InPost",    "", 0xFFCD00, C::Delivery},
          {"inpost.pl", "inpost.co.uk", "inpost.eu"}, {}, {"inpost"} },
        { {"postnl",    "PostNL",    "", 0xFF6600, C::Delivery},
          {"postnl.nl"}, {}, {"postnl"} },
        { {"bpost",     "bpost",     "", 0xEF2637, C::Delivery},
          {"bpost.be"}, {}, {"bpost"} },
        { {"colissimo", "Colissimo", "", 0xFFCC00, C::Delivery},
          {"colissimo.fr"}, {}, {"colissimo"} },
        { {"chronopost", "Chronopost", "", 0x0057A4, C::Delivery},
          {"chronopost.fr"}, {}, {"chronopost"} },
        { {"swisspost", "Swiss Post", "", 0xFFCC00, C::Delivery},
          {"post.ch"}, {}, {"swiss post", "post.ch"} },
        { {"austrianpost", "Österreichische Post", "", 0xFFDC00, C::Delivery},
          {"post.at"}, {}, {"post.at", "austrian post"} },
        { {"postnord",  "PostNord",  "", 0x00A0D6, C::Delivery},
          {"postnord.com", "postnord.se", "postnord.dk"}, {}, {"postnord"} },
        { {"posteitaliane", "Poste Italiane", "", 0x0047BB, C::Delivery},
          {"poste.it", "posteitaliane.it"}, {}, {"poste italiane"} },
        { {"correos",   "Correos",   "", 0xFFCD00, C::Delivery},
          {"correos.es"}, {}, {"correos"} },
        { {"ctt",       "CTT",       "", 0xDF0024, C::Delivery},
          {"ctt.pt"}, {}, {"ctt correios"} },
        { {"canadapost", "Canada Post", "", 0xDA291C, C::Delivery},
          {"canadapost.ca", "canadapost-postescanada.ca"}, {}, {"canada post"} },
        { {"auspost",   "Australia Post", "", 0xDC1928, C::Delivery},
          {"auspost.com.au"}, {}, {"auspost"} },

        // ── Travel and transport ────────────────────────────────────────────
        { {"expedia",   "Expedia",   "", 0xFDDB32, C::Travel},
          {"expedia.com", "expediamail.com", "expedia.de", "expedia.co.uk"}, {}, {"expedia"} },
        { {"hotelscom", "Hotels.com", "", 0xD32F2F, C::Travel},
          {"hotels.com"}, {}, {"hotels.com"} },
        { {"agoda",     "Agoda",     "", 0x5392F9, C::Travel},
          {"agoda.com"}, {}, {"agoda"} },
        { {"tripadvisor", "Tripadvisor", "", 0x34E0A1, C::Travel},
          {"tripadvisor.com"}, {}, {"tripadvisor"} },
        { {"trivago",   "trivago",   "", 0x007FAD, C::Travel},
          {"trivago.com"}, {}, {"trivago"} },
        { {"uber",      "Uber",      "", 0x111111, C::Travel},
          {"uber.com"}, {}, {"uber eats"} },
        { {"lyft",      "Lyft",      "", 0xFF00BF, C::Travel},
          {"lyft.com"}, {}, {"lyft"} },
        { {"ryanair",   "Ryanair",   "", 0x073590, C::Travel},
          {"ryanair.com"}, {}, {"ryanair"} },
        { {"easyjet",   "easyJet",   "", 0xFF6600, C::Travel},
          {"easyjet.com"}, {}, {"easyjet"} },
        { {"lufthansa", "Lufthansa", "", 0x05164D, C::Travel},
          {"lufthansa.com"}, {}, {"lufthansa", "miles & more"} },
        { {"britishairways", "British Airways", "", 0x075AAA, C::Travel},
          {"britishairways.com", "ba.com"}, {}, {"british airways"} },
        { {"klm",       "KLM",       "", 0x00A1DE, C::Travel},
          {"klm.com"}, {}, {"klm"} },
        { {"airfrance", "Air France", "", 0x002157, C::Travel},
          {"airfrance.com", "airfrance.fr"}, {}, {"air france", "flying blue"} },
        { {"delta",     "Delta Air Lines", "", 0xC8102E, C::Travel},
          {"delta.com"}, {}, {"delta air lines", "delta airlines", "skymiles"} },
        { {"united",    "United Airlines", "", 0x005DAA, C::Travel},
          {"united.com"}, {}, {"united airlines", "mileageplus"} },
        { {"americanairlines", "American Airlines", "", 0x0078D2, C::Travel},
          {"aa.com"}, {}, {"american airlines", "aadvantage"} },
        { {"emirates",  "Emirates",  "", 0xD71921, C::Travel},
          {"emirates.com"}, {}, {"emirates airline", "emirates skywards"}, KW },
        { {"qatarairways", "Qatar Airways", "", 0x5C0632, C::Travel},
          {"qatarairways.com"}, {}, {"qatar airways"} },
        { {"deutschebahn", "Deutsche Bahn", "", 0xEC0016, C::Travel},
          {"bahn.de", "deutschebahn.com"}, {}, {"deutsche bahn", "bahncard"} },
        { {"sncf",      "SNCF",      "", 0x0C131F, C::Travel},
          {"sncf.com", "sncf-connect.com"}, {}, {"sncf"} },
        { {"trainline", "Trainline", "", 0x01C3A7, C::Travel},
          {"thetrainline.com"}, {}, {"trainline"} },
        { {"amtrak",    "Amtrak",    "", 0x1A5B8C, C::Travel},
          {"amtrak.com"}, {}, {"amtrak"} },

        // ── Streaming and media ─────────────────────────────────────────────
        { {"disneyplus", "Disney+",  "", 0x113CCF, C::Media},
          {"disneyplus.com", "disney.com"}, {}, {"disney plus", "disneyplus"} },
        { {"hulu",      "Hulu",      "", 0x1CE783, C::Media},
          {"hulu.com"}, {}, {"hulu"} },
        { {"max",       "Max",       "", 0x002BE7, C::Media},
          {"max.com", "hbomax.com"}, {}, {"hbo max", "hbomax"}, KW },
        { {"paramountplus", "Paramount+", "", 0x0064FF, C::Media},
          {"paramountplus.com"}, {}, {"paramount plus", "paramountplus"} },
        { {"dazn",      "DAZN",      "", 0x111111, C::Media},
          {"dazn.com"}, {}, {"dazn"} },
        { {"crunchyroll", "Crunchyroll", "", 0xF47521, C::Media},
          {"crunchyroll.com"}, {}, {"crunchyroll"} },
        { {"deezer",    "Deezer",    "", 0xA238FF, C::Media},
          {"deezer.com"}, {}, {"deezer"} },
        { {"soundcloud", "SoundCloud", "", 0xFF5500, C::Media},
          {"soundcloud.com"}, {}, {"soundcloud"} },

        // ── Cloud, hosting, file sharing and business software ──────────────
        { {"cloudflare", "Cloudflare", "", 0xF38020, C::CloudHosting},
          {"cloudflare.com"}, {}, {"cloudflare"} },
        { {"digitalocean", "DigitalOcean", "", 0x0080FF, C::CloudHosting},
          {"digitalocean.com"}, {}, {"digitalocean", "digital ocean"} },
        { {"heroku",    "Heroku",    "", 0x430098, C::CloudHosting},
          {"heroku.com"}, {}, {"heroku"} },
        { {"vercel",    "Vercel",    "", 0x111111, C::CloudHosting},
          {"vercel.com"}, {}, {"vercel"} },
        { {"netlify",   "Netlify",   "", 0x00C7B7, C::CloudHosting},
          {"netlify.com"}, {}, {"netlify"} },
        { {"linode",    "Linode",    "", 0x00B159, C::CloudHosting},
          {"linode.com"}, {}, {"linode"} },
        { {"akamai",    "Akamai",    "", 0x0099CC, C::CloudHosting},
          {"akamai.com"}, {}, {"akamai"} },
        { {"ovhcloud",  "OVHcloud",  "", 0x000E9C, C::CloudHosting},
          {"ovhcloud.com", "ovh.com", "ovh.net", "ovh.de", "ovh.co.uk", "ovh.ie"}, {},
          {"ovh"} },
        { {"hetzner",   "Hetzner",   "", 0xD50C2D, C::CloudHosting},
          {"hetzner.com", "hetzner.de", "hetzner.cloud"}, {}, {"hetzner"} },
        { {"ionos",     "IONOS",     "", 0x003D8F, C::CloudHosting},
          {"ionos.com", "ionos.de", "ionos.co.uk", "ionos.fr", "ionos.es"}, {}, {"ionos"} },
        { {"1und1",     "1&1",       "", 0x003D8F, C::Telecom},
          {"1und1.de"}, {}, {"1und1", "1&1"} },
        { {"strato",    "STRATO",    "", 0xFF8800, C::CloudHosting},
          {"strato.de", "strato.com"}, {}, {"strato"} },
        { {"hostinger", "Hostinger", "", 0x673DE6, C::CloudHosting},
          {"hostinger.com"}, {}, {"hostinger"} },
        { {"bluehost",  "Bluehost",  "", 0x3575D3, C::CloudHosting},
          {"bluehost.com"}, {}, {"bluehost"} },
        { {"hostgator", "HostGator", "", 0xFFCF00, C::CloudHosting},
          {"hostgator.com"}, {}, {"hostgator"} },
        { {"siteground", "SiteGround", "", 0x7E57C2, C::CloudHosting},
          {"siteground.com"}, {}, {"siteground"} },
        { {"dreamhost", "DreamHost", "", 0x0073EC, C::CloudHosting},
          {"dreamhost.com"}, {}, {"dreamhost"} },
        { {"wpengine",  "WP Engine", "", 0x0ECAD4, C::CloudHosting},
          {"wpengine.com"}, {}, {"wp engine", "wpengine"} },
        { {"wordpress", "WordPress.com", "", 0x21759B, C::CloudHosting},
          {"wordpress.com", "automattic.com"}, {}, {"wordpress.com"} },
        { {"wix",       "Wix",       "", 0x0C6EFC, C::CloudHosting},
          {"wix.com"}, {}, {"wix"} },
        { {"squarespace", "Squarespace", "", 0x111111, C::CloudHosting},
          {"squarespace.com"}, {}, {"squarespace"} },
        { {"box",       "Box",       "", 0x0061D5, C::CloudHosting},
          {"box.com"}, {}, {"box.com"}, KW },
        { {"mega",      "MEGA",      "", 0xD9272E, C::CloudHosting},
          {"mega.nz", "mega.io"}, {}, {"mega.nz"}, KW },
        { {"pcloud",    "pCloud",    "", 0x17BED0, C::CloudHosting},
          {"pcloud.com"}, {}, {"pcloud"} },
        { {"backblaze", "Backblaze", "", 0xE21E29, C::CloudHosting},
          {"backblaze.com"}, {}, {"backblaze"} },
        { {"wetransfer", "WeTransfer", "", 0x409FFF, C::CloudHosting},
          {"wetransfer.com"}, {}, {"wetransfer"} },
        { {"docusign",  "DocuSign",  "", 0xFFCC22, C::Technology},
          {"docusign.com", "docusign.net"}, {}, {"docusign"} },
        { {"adobe",     "Adobe",     "", 0xFA0F00, C::Technology},
          {"adobe.com", "adobesign.com"}, {}, {"adobe", "acrobat"} },
        { {"atlassian", "Atlassian", "", 0x0052CC, C::Technology},
          {"atlassian.com", "atlassian.net", "trello.com", "bitbucket.org"}, {},
          {"atlassian", "trello", "bitbucket"} },
        { {"notion",    "Notion",    "", 0x111111, C::Technology},
          {"notion.so", "makenotion.com"}, {}, {"notion.so"}, KW },
        { {"salesforce", "Salesforce", "", 0x00A1E0, C::Technology},
          {"salesforce.com"}, {}, {"salesforce"} },
        { {"okta",      "Okta",      "", 0x007DC1, C::Technology},
          {"okta.com"}, {}, {"okta"} },
        { {"webex",     "Webex",     "", 0x00BCEB, C::Technology},
          {"webex.com", "cisco.com"}, {}, {"webex", "cisco"} },
        { {"intuit",    "Intuit",    "", 0x236CFF, C::Technology},
          {"intuit.com"}, {}, {"quickbooks", "turbotax"} },
        { {"xero",      "Xero",      "", 0x13B5EA, C::Technology},
          {"xero.com"}, {}, {"xero"} },
        { {"mailchimp", "Mailchimp", "", 0xFFE01B, C::Technology},
          {"mailchimp.com"}, {}, {"mailchimp"} },
        { {"gitlab",    "GitLab",    "", 0xFC6D26, C::Technology},
          {"gitlab.com"}, {}, {"gitlab"} },
        { {"docker",    "Docker",    "", 0x2496ED, C::Technology},
          {"docker.com"}, {}, {"docker hub"} },
        { {"figma",     "Figma",     "", 0xF24E1E, C::Technology},
          {"figma.com"}, {}, {"figma"} },
        { {"canva",     "Canva",     "", 0x00C4CC, C::Technology},
          {"canva.com"}, {}, {"canva"} },

        // ── Domain registrars and registries ────────────────────────────────
        // "Your domain expires" is one of the oldest phishing lures there is.
        { {"godaddy",   "GoDaddy",   "", 0x1BDBDB, C::DomainRegistrar},
          {"godaddy.com"}, {}, {"godaddy"} },
        { {"namecheap", "Namecheap", "", 0xDE3723, C::DomainRegistrar},
          {"namecheap.com"}, {}, {"namecheap"} },
        { {"networksolutions", "Network Solutions", "", 0x2B7A0B, C::DomainRegistrar},
          {"networksolutions.com"}, {}, {"networksolutions"} },
        { {"namecom",   "Name.com",  "", 0x2C7EBF, C::DomainRegistrar},
          {"name.com"}, {}, {"name.com"} },
        { {"porkbun",   "Porkbun",   "", 0xEF7878, C::DomainRegistrar},
          {"porkbun.com"}, {}, {"porkbun"} },
        { {"dynadot",   "Dynadot",   "", 0x0E66B3, C::DomainRegistrar},
          {"dynadot.com"}, {}, {"dynadot"} },
        { {"gandi",     "Gandi",     "", 0x5CC8C4, C::DomainRegistrar},
          {"gandi.net"}, {}, {"gandi"} },
        { {"hover",     "Hover",     "", 0x2AB2C1, C::DomainRegistrar},
          {"hover.com"}, {}, {"hover.com"}, KW },
        { {"inwx",      "INWX",      "", 0x00346E, C::DomainRegistrar},
          {"inwx.de", "inwx.com"}, {}, {"inwx"} },
        { {"uniteddomains", "united-domains", "", 0x8DBA21, C::DomainRegistrar},
          {"united-domains.de"}, {}, {"united-domains", "united domains"} },
        { {"denic",     "DENIC",     "", 0x003C64, C::DomainRegistrar},
          {"denic.de"}, {}, {"denic"} },
        { {"nominet",   "Nominet",   "", 0x6A1F7A, C::DomainRegistrar},
          {"nominet.uk"}, {}, {"nominet"} },
        { {"icann",     "ICANN",     "", 0x1A3C6E, C::DomainRegistrar},
          {"icann.org"}, {}, {"icann"} },
        { {"verisign",  "Verisign",  "", 0x0A3D7E, C::DomainRegistrar},
          {"verisign.com"}, {}, {"verisign"} },

        // ── Tax offices and government agencies ─────────────────────────────
        // Most of these never mail a refund or a fine out of the blue, which
        // is exactly why "the IRS" in a display name from elsewhere matters.
        { {"irs",       "IRS",       "", 0x00599C, C::Government},
          {"irs.gov"}, {}, {"internal revenue service"} },
        { {"ssa",       "Social Security Administration", "", 0x112E51, C::Government},
          {"ssa.gov"}, {}, {"ssa.gov"} },
        { {"uscis",     "USCIS",     "", 0x003366, C::Government},
          {"uscis.gov"}, {}, {"uscis"} },
        { {"medicare",  "Medicare",  "", 0x0B4778, C::Government},
          {"medicare.gov"}, {}, {"medicare.gov"}, KW },
        { {"fbi",       "FBI",       "", 0x1F3A60, C::Government},
          {"fbi.gov", "ic3.gov"}, {}, {"federal bureau of investigation", "fbi.gov", "ic3.gov"}, KW },
        { {"hmrc",      "HMRC",      "", 0x00703C, C::Government},
          {"hmrc.gov.uk", "tax.service.gov.uk"}, {}, {"hm revenue"} },
        { {"dvla",      "DVLA",      "", 0x00703C, C::Government},
          {"dvla.gov.uk"}, {}, {"dvla"} },
        { {"tvlicensing", "TV Licensing", "", 0xE4002B, C::Government},
          {"tvlicensing.co.uk"}, {}, {"tv licensing", "tv licence"} },
        { {"cra",       "Canada Revenue Agency", "", 0x26374A, C::Government},
          {"canada.ca", "cra-arc.gc.ca"}, {}, {"canada revenue agency"} },
        { {"ato",       "Australian Taxation Office", "", 0x1B365D, C::Government},
          {"ato.gov.au"}, {}, {"australian taxation office"} },
        { {"mygov",     "myGov",     "", 0x313131, C::Government},
          {"my.gov.au", "servicesaustralia.gov.au"}, {}, {"mygov", "centrelink", "services australia"} },
        { {"elster",    "ELSTER",    "", 0x00586F, C::Government},
          {"elster.de"}, {}, {"elster"} },
        { {"bzst",      "Bundeszentralamt für Steuern", "", 0x000000, C::Government},
          {"bzst.de"}, {}, {"bzst", "bundeszentralamt"} },
        { {"rundfunkbeitrag", "ARD ZDF Beitragsservice", "", 0x1B3D6D, C::Government},
          {"rundfunkbeitrag.de"}, {}, {"rundfunkbeitrag", "beitragsservice"} },
        { {"dgfip",     "Impots.gouv.fr", "", 0x000091, C::Government},
          {"impots.gouv.fr"}, {}, {"impots.gouv", "dgfip"} },
        { {"antai",     "ANTAI",     "", 0x000091, C::Government},
          {"antai.gouv.fr"}, {}, {"antai"} },
        { {"ameli",     "Ameli",     "", 0x0C419A, C::Government},
          {"ameli.fr"}, {}, {"assurance maladie"} },
        { {"incometaxindia", "Income Tax Department", "", 0x1C4587, C::Government},
          {"incometax.gov.in"}, {}, {"income tax department"} },

        // ── Telecom providers ───────────────────────────────────────────────
        // Not here: providers that are also consumer mailbox domains (Orange,
        // SFR, Sky, Virgin Media, Rogers) - their addresses are people.
        { {"verizon",   "Verizon",   "", 0xCD040B, C::Telecom},
          {"verizon.com", "verizonwireless.com"}, {}, {"verizon"} },
        { {"att",       "AT&T",      "", 0x00A8E0, C::Telecom},
          {"att.com"}, {}, {"at&t"} },
        { {"tmobile",   "T-Mobile",  "", 0xE20074, C::Telecom},
          {"t-mobile.com"}, {}, {"t-mobile", "tmobile"} },
        { {"xfinity",   "Xfinity",   "", 0x6138F5, C::Telecom},
          {"xfinity.com"}, {}, {"xfinity"} },
        { {"telekom",   "Telekom",   "", 0xE20074, C::Telecom},
          {"telekom.de", "telekom.com"}, {}, {"telekom"} },
        { {"vodafone",  "Vodafone",  "", 0xE60000, C::Telecom},
          {"vodafone.com", "vodafone.de", "vodafone.co.uk", "vodafone.it", "vodafone.es",
           "vodafone.nl"}, {}, {"vodafone"} },
        // Two-letter names: recognised, claimed only through longer words.
        { {"o2",        "O2",        "", 0x0019A5, C::Telecom},
          {"o2.co.uk", "o2online.de"}, {}, {"o2online"} },
        { {"ee",        "EE",        "", 0x00B5B0, C::Telecom},
          {"ee.co.uk"}, {}, {} },
        { {"bt",        "BT",        "", 0x5514B4, C::Telecom},
          {"bt.com"}, {}, {"bt broadband", "bt group"} },
        { {"swisscom",  "Swisscom",  "", 0x001155, C::Telecom},
          {"swisscom.ch", "swisscom.com"}, {}, {"swisscom"} },
        { {"telstra",   "Telstra",   "", 0x0099F8, C::Telecom},
          {"telstra.com", "telstra.com.au"}, {}, {"telstra"} },
        { {"optus",     "Optus",     "", 0x00837E, C::Telecom},
          {"optus.com.au"}, {}, {"optus"} },
        { {"bell",      "Bell",      "", 0x00549A, C::Telecom},
          {"bell.ca"}, {}, {"bell canada"}, KW },
        { {"movistar",  "Movistar",  "", 0x019DF4, C::Telecom},
          {"movistar.es"}, {}, {"movistar"} },
        { {"bouygues",  "Bouygues Telecom", "", 0x009DCC, C::Telecom},
          {"bouyguestelecom.fr"}, {}, {"bouygues"} },
        { {"kpn",       "KPN",       "", 0x00C300, C::Telecom},
          {"kpn.com"}, {}, {"kpn"} },
        { {"proximus",  "Proximus",  "", 0x5C2D91, C::Telecom},
          {"proximus.be"}, {}, {"proximus"} },
        { {"telia",     "Telia",     "", 0x990AE3, C::Telecom},
          {"telia.com", "telia.se"}, {}, {"telia"} },
        { {"jio",       "Jio",       "", 0x0F3CC9, C::Telecom},
          {"jio.com"}, {}, {"reliance jio"} },
        { {"airtel",    "Airtel",    "", 0xE40000, C::Telecom},
          {"airtel.in"}, {}, {"airtel"} },

        // ── Game stores and platforms ───────────────────────────────────────
        { {"steam",     "Steam",     "", 0x171A21, C::Gaming},
          {"steampowered.com", "steamcommunity.com"}, {},
          {"steam support", "steam account", "steam guard", "steampowered",
           "steamcommunity", "steam community"}, KW },
        { {"epicgames", "Epic Games", "", 0x313131, C::Gaming},
          {"epicgames.com"}, {}, {"epic games", "epicgames", "fortnite"} },
        { {"playstation", "PlayStation", "", 0x003791, C::Gaming},
          {"playstation.com", "sonyentertainmentnetwork.com"}, {}, {"playstation", "psn"} },
        { {"nintendo",  "Nintendo",  "", 0xE60012, C::Gaming},
          {"nintendo.com", "nintendo.net", "nintendo.de", "nintendo.co.uk", "nintendo.co.jp"}, {},
          {"nintendo"} },
        { {"roblox",    "Roblox",    "", 0x111111, C::Gaming},
          {"roblox.com"}, {}, {"roblox", "robux"} },
        { {"riotgames", "Riot Games", "", 0xD13639, C::Gaming},
          {"riotgames.com"}, {}, {"riot games", "league of legends", "valorant"} },
        { {"blizzard",  "Blizzard",  "", 0x148EFF, C::Gaming},
          {"blizzard.com", "battle.net"}, {}, {"blizzard", "battle.net"} },
        { {"ea",        "EA",        "", 0xFF4747, C::Gaming},
          {"ea.com"}, {}, {"electronic arts"} },
        { {"ubisoft",   "Ubisoft",   "", 0x111111, C::Gaming},
          {"ubisoft.com"}, {}, {"ubisoft"} },
        { {"minecraft", "Minecraft", "", 0x62B47A, C::Gaming},
          {"minecraft.net", "mojang.com"}, {}, {"minecraft", "mojang"} },

        // ── Security software, password managers, VPNs ──────────────────────
        // "Your Norton subscription renewed - call this number" is the
        // classic tech-support scam.
        { {"norton",    "Norton",    "", 0xFFC700, C::Security},
          {"norton.com", "nortonlifelock.com"}, {}, {"norton antivirus", "norton 360"} },
        { {"mcafee",    "McAfee",    "", 0xC01818, C::Security},
          {"mcafee.com"}, {}, {"mcafee"} },
        { {"avast",     "Avast",     "", 0xFF7800, C::Security},
          {"avast.com"}, {}, {"avast"} },
        { {"avg",       "AVG",       "", 0x00A54F, C::Security},
          {"avg.com"}, {}, {"avg antivirus"}, KW },
        { {"kaspersky", "Kaspersky", "", 0x00A88E, C::Security},
          {"kaspersky.com"}, {}, {"kaspersky"} },
        { {"bitdefender", "Bitdefender", "", 0xED1C24, C::Security},
          {"bitdefender.com"}, {}, {"bitdefender"} },
        { {"malwarebytes", "Malwarebytes", "", 0x0D3ECC, C::Security},
          {"malwarebytes.com"}, {}, {"malwarebytes"} },
        { {"eset",      "ESET",      "", 0x00A3A1, C::Security},
          {"eset.com"}, {}, {"eset"} },
        { {"lastpass",  "LastPass",  "", 0xD32D27, C::Security},
          {"lastpass.com"}, {}, {"lastpass"} },
        { {"1password", "1Password", "", 0x0572EC, C::Security},
          {"1password.com"}, {}, {"1password"} },
        { {"bitwarden", "Bitwarden", "", 0x175DDC, C::Security},
          {"bitwarden.com"}, {}, {"bitwarden"} },
        { {"nordvpn",   "NordVPN",   "", 0x4687FF, C::Security},
          {"nordvpn.com", "nordaccount.com", "nordsecurity.com"}, {}, {"nordvpn", "nord account"} },
        { {"expressvpn", "ExpressVPN", "", 0xDA3940, C::Security},
          {"expressvpn.com"}, {}, {"expressvpn"} },
    };
}

} // namespace

const std::vector<BrandRule>& SenderBrandRules() {
    static const std::vector<BrandRule> rules = [] {
        std::vector<BrandRule> v = BuildRules();
        for (BrandRule& rule : v) {
            if (!rule.brand.iconUrl.empty() || rule.domains.empty()) continue;
            const std::string& d = rule.domains.front();
            const bool apex = d.find('.') == d.rfind('.');   // "chase.com", not "x.co.uk"
            rule.brand.iconUrl = "https://" + std::string(apex ? "www." : "") + d + "/favicon.ico";
        }
        return v;
    }();
    return rules;
}

} // namespace UltraMail
