#!/usr/bin/env python3
"""Generates UltraCanvas/Plugins/Documents/Word/UltraCanvasSymbolFontTable.inc.

The table maps the 8-bit codes of the Windows symbol fonts (Symbol,
Wingdings, Wingdings 2, Wingdings 3, Webdings) to Unicode. Documents store a
character in one of these fonts as its font code (or as U+F000 + code); on a
system without the font it draws as a wrong letter unless it is mapped.

Source data: the npm package dingbat-to-unicode (BSD-2-Clause,
Copyright (c) 2021 Michael Williamson), which follows the Unicode mappings
published with Unicode 7.0. Usage:

    npm pack dingbat-to-unicode && tar xzf dingbat-to-unicode-*.tgz
    python3 scripts/generate_symbol_font_map.py package/dist/dingbats.js
"""
import re
import sys
from pathlib import Path

FONTS = [("SYMBOL", "Symbol"), ("WINGDINGS", "Wingdings"), ("WINGDINGS 2", "Wingdings2"),
         ("WINGDINGS 3", "Wingdings3"), ("WEBDINGS", "Webdings")]

OUT = Path(__file__).resolve().parent.parent / "UltraCanvas/Plugins/Documents/Word/UltraCanvasSymbolFontTable.inc"


def parse(js: str):
    tables = {}
    for match in re.finditer(r'"([A-Z0-9 ]+)":\s*\{([^}]*)\}', js):
        entries = dict((int(k), int(v)) for k, v in re.findall(r'(\d+):\s*(\d+)', match.group(2)))
        tables[match.group(1)] = entries
    return tables


def main():
    js = Path(sys.argv[1]).read_text(encoding="utf-8")
    tables = parse(js)
    lines = [
        "// Plugins/Documents/Word/UltraCanvasSymbolFontTable.inc",
        "// GENERATED by scripts/generate_symbol_font_map.py - do not edit by hand.",
        "// Codes 0x20..0xFF of the Windows symbol fonts -> Unicode (0 = unmapped).",
        "//",
        "// Data from dingbat-to-unicode (https://github.com/mwilliamson/dingbat-to-unicode):",
        "// Copyright (c) 2021, Michael Williamson. All rights reserved.",
        "// Redistribution and use in source and binary forms, with or without",
        "// modification, are permitted provided that the following conditions are met:",
        "// 1. Redistributions of source code must retain the above copyright notice,",
        "//    this list of conditions and the following disclaimer.",
        "// 2. Redistributions in binary form must reproduce the above copyright notice,",
        "//    this list of conditions and the following disclaimer in the documentation",
        "//    and/or other materials provided with the distribution.",
        "// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"",
        "// AND ANY EXPRESS OR IMPLIED WARRANTIES ARE DISCLAIMED. See THIRD_PARTY_LICENSES.md.",
        "",
    ]
    for key, name in FONTS:
        table = tables[key]
        values = [table.get(code, 0) for code in range(0x20, 0x100)]
        lines.append(f"constexpr uint32_t k{name}ToUnicode[224] = {{")
        for row in range(0, 224, 8):
            lines.append("    " + ", ".join(f"0x{v:05X}" for v in values[row:row + 8]) + ",")
        lines.append("};")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
