#!/usr/bin/env python3
# scripts/generate_face_cascade.py
# Turn the vendored OpenCV Haar cascade into the C++ table VideoFX's face
# detector compiles in, so the detector needs neither the XML at run time nor
# Python at build time.
#
#   python3 scripts/generate_face_cascade.py           write the table
#   python3 scripts/generate_face_cascade.py --check   fail if it is out of date
#
# Reads  UltraCanvas/third_party/opencv_haarcascade/haarcascade_frontalface_alt.xml
# Writes VideoFX/core/VideoFXFaceCascade.inc
#
# Only stump-based HAAR BOOST cascades (OpenCV's "new" format) are read - one
# split per weak classifier, untilted rectangles - which is what the frontal
# face cascades are. Anything else stops with an error rather than producing a
# table that would silently detect nothing.
#
# Version: 1.0.0
# Last Modified: 2026-10-07
# Author: UltraCanvas Framework

import argparse
import hashlib
import pathlib
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "UltraCanvas/third_party/opencv_haarcascade/haarcascade_frontalface_alt.xml"
TARGET = ROOT / "VideoFX/core/VideoFXFaceCascade.inc"


def numbers(text):
    return [float(v) for v in text.split()]


def f32(v):
    # Shortest text that reads back as the same float, with an f suffix
    s = repr(float(v))
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def generate(xml_bytes):
    root = ET.fromstring(xml_bytes)
    cascade = root.find("cascade")
    if cascade is None:
        sys.exit("generate_face_cascade: no <cascade> (an old-format file?)")
    if cascade.findtext("stageType").strip() != "BOOST" or cascade.findtext("featureType").strip() != "HAAR":
        sys.exit("generate_face_cascade: only BOOST / HAAR cascades are supported")
    width = int(cascade.findtext("width"))
    height = int(cascade.findtext("height"))

    stages, weaks = [], []
    for stage in cascade.find("stages"):
        first = len(weaks)
        for weak in stage.find("weakClassifiers"):
            nodes = weak.findtext("internalNodes").split()
            leaves = numbers(weak.findtext("leafValues"))
            # A stump: "left right featureIndex threshold" with both children leaves
            if len(nodes) != 4 or nodes[0] != "0" or nodes[1] != "-1" or len(leaves) != 2:
                sys.exit("generate_face_cascade: only stump classifiers are supported")
            weaks.append((int(nodes[2]), float(nodes[3]), leaves[0], leaves[1]))
        stages.append((first, len(weaks) - first, float(stage.findtext("stageThreshold"))))

    features = []
    for feature in cascade.find("features"):
        if (feature.findtext("tilted") or "0").strip() != "0":
            sys.exit("generate_face_cascade: tilted features are not supported")
        rects = []
        for r in feature.find("rects"):
            x, y, w, h, weight = r.text.split()
            rects.append((int(x), int(y), int(w), int(h), float(weight)))
        if not 1 <= len(rects) <= 3:
            sys.exit("generate_face_cascade: a feature with %d rectangles" % len(rects))
        while len(rects) < 3:
            rects.append((0, 0, 0, 0, 0.0))
        features.append(rects)
    if any(w[0] >= len(features) for w in weaks):
        sys.exit("generate_face_cascade: a classifier names a feature that does not exist")

    digest = hashlib.sha256(xml_bytes).hexdigest()
    out = []
    out.append("// VideoFX/core/VideoFXFaceCascade.inc")
    out.append("// GENERATED by scripts/generate_face_cascade.py - do not edit.")
    out.append("// OpenCV's haarcascade_frontalface_alt.xml (Rainer Lienhart; Intel License")
    out.append("// Agreement For Open Source Computer Vision Library, 3-clause BSD-style -")
    out.append("// UltraCanvas/third_party/opencv_haarcascade/LICENSE), as compact tables.")
    out.append("// Source SHA-256: " + digest)
    out.append("// Included by VideoFXFaces.cpp only.")
    out.append("")
    out.append("constexpr int kCascadeWidth = %d;" % width)
    out.append("constexpr int kCascadeHeight = %d;" % height)
    out.append("")
    out.append("// first classifier, classifiers, threshold the stage's sum must reach")
    out.append("constexpr CascadeStage kCascadeStages[] = {")
    for first, count, threshold in stages:
        out.append("    {%d, %d, %s}," % (first, count, f32(threshold)))
    out.append("};")
    out.append("")
    out.append("// feature, threshold (x the window's deviation), value below, value at or above")
    out.append("constexpr CascadeWeak kCascadeWeaks[] = {")
    for feature, threshold, left, right in weaks:
        out.append("    {%d, %s, %s, %s}," % (feature, f32(threshold), f32(left), f32(right)))
    out.append("};")
    out.append("")
    out.append("// up to three weighted rectangles in the %dx%d window (weight 0 = unused)" % (width, height))
    out.append("constexpr CascadeFeature kCascadeFeatures[] = {")
    for rects in features:
        parts = ", ".join("{%d, %d, %d, %d, %s}" % (x, y, w, h, f32(wt)) for x, y, w, h, wt in rects)
        out.append("    {{%s}}," % parts)
    out.append("};")
    out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the table is out of date")
    args = parser.parse_args()
    text = generate(SOURCE.read_bytes())
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            print("generate_face_cascade: %s is out of date - run python3 scripts/generate_face_cascade.py"
                  % TARGET.relative_to(ROOT))
            return 1
        print("generate_face_cascade: up to date")
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print("generate_face_cascade: wrote %s" % TARGET.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
