#!/usr/bin/env python3
"""Summarise the feasibility runs (run.sh) as Markdown tables.

    python3 summarise.py /tmp/ultraweb-feasibility/runs
"""
import json
import math
import pathlib
import sys

APPS = ["react", "ng-zoneless", "ng-zone"]
ENGINES = ["node", "node-jitless", "qjs", "wasmtime", "wamr-fastjit", "wamr-interp"]
ENGINE_LABEL = {
    "node": "V8 JIT (Node)",
    "node-jitless": "V8 no JIT",
    "qjs": "QuickJS native",
    "wasmtime": "QuickJS-in-WASM, wasmtime",
    "wamr-fastjit": "QuickJS-in-WASM, WAMR fast JIT",
    "wamr-interp": "QuickJS-in-WASM, WAMR interpreter",
}
OPS = ["create1k", "replace1k", "update10th", "select", "swap", "remove",
       "clear1k", "create10k", "clear10k", "append1k", "clear2k"]


def load(path):
    try:
        lines = [l for l in path.read_text().splitlines() if l.startswith("{")]
        return json.loads(lines[-1]) if lines else None
    except FileNotFoundError:
        return None


def fmt(v):
    return "—" if v is None else (f"{v:.0f}" if v >= 100 else f"{v:.1f}")


def main(runs):
    runs = pathlib.Path(runs)
    print("# UltraWeb feasibility results\n")
    print("Generated by `summarise.py` from the runs in `run.sh` (see [README.md](README.md) for the")
    print("method and the caveats). Script time only: no layout or paint, and a JavaScript DOM")
    print("(linkedom) inside the measured engine.")
    for app in APPS:
        res = {e: load(runs / f"{app}-{e}.json") for e in ENGINES}
        name = next((r["app"] for r in res.values() if r), app)
        engines = [e for e in ENGINES if res[e]]
        if not engines:
            continue
        print(f"\n### {name} — median ms per operation\n")
        print("| Operation | " + " | ".join(ENGINE_LABEL[e] for e in engines) + " |")
        print("|---|" + "---:|" * len(engines))
        for op in OPS:
            cells = []
            for e in engines:
                r = res[e]
                cells.append("**fail**" if not r["ok"] else fmt(r["ops"].get(op)))
            print(f"| {op} | " + " | ".join(cells) + " |")
        print("| bundle parse + run | " + " | ".join(fmt(res[e].get("bundleEvalMs")) for e in engines) + " |")
        base = res.get("node")
        if base and base["ok"]:
            ratios = []
            for e in engines:
                r = res[e]
                if not r["ok"]:
                    ratios.append("—"); continue
                logs = [math.log(r["ops"][o] / base["ops"][o]) for o in OPS]
                ratios.append(f"{math.exp(sum(logs) / len(logs)):.1f}×")
            print("| **slowdown vs V8 JIT (geometric mean)** | " + " | ".join(ratios) + " |")
        for e in engines:
            if res[e] and not res[e]["ok"]:
                print(f"\n{ENGINE_LABEL[e]} failed: `{res[e]['error'][:300]}`")

    print("\n### Time inside the JavaScript test DOM (linkedom), recording runs\n")
    print("| App | Engine | create1k total / in DOM | create10k total / in DOM | DOM calls for create1k |")
    print("|---|---|---|---|---:|")
    for app in APPS:
        for e in ["node", "qjs"]:
            r = load(runs / f"{app}-{e}-surface.json")
            if not r or not r["ok"]:
                continue
            c1, c10 = r["ops"]["create1k"], r["ops"]["create10k"]
            d1, d10 = r["dom"]["create1k"]["domMs"], r["dom"]["create10k"]["domMs"]
            print(f"| {r['app']} | {ENGINE_LABEL[e]} | {fmt(c1)} / {fmt(d1)} ms ({100 * d1 / c1:.0f}%) "
                  f"| {fmt(c10)} / {fmt(d10)} ms ({100 * d10 / c10:.0f}%) | {r['dom']['create1k']['calls']} |")

    print("\n### DOM and window members each framework used\n")
    surfaces = {}
    for app in APPS:
        r = load(runs / f"{app}-node-surface.json")
        if r and r["ok"]:
            surfaces[r["app"]] = r
    every = sorted(set(n for r in surfaces.values() for n, _ in r["surface"]))
    print("| Member | " + " | ".join(surfaces) + " |")
    print("|---|" + "---:|" * len(surfaces))
    for n in every:
        row = []
        for r in surfaces.values():
            d = dict(r["surface"])
            row.append(str(d[n]) if n in d else "")
        print(f"| `{n}` | " + " | ".join(row) + " |")
    print("\nGlobals looked up but not provided (feature probes):\n")
    for app, r in surfaces.items():
        print(f"- {app}: " + ", ".join(f"`{p}`" for p in r.get("probes", [])))

    print("\n### Parsing, and loading cached bytecode instead\n")
    print("| Bundle | Size | QuickJS native: compile | load bytecode | QuickJS-in-WASM (wasmtime): compile | load bytecode |")
    print("|---|---:|---:|---:|---:|---:|")
    for f in ["react.js", "ng-zoneless.js", "typescript.js"]:
        n, w = load(runs / f"parse-qjs-{f}.json"), load(runs / f"parse-wasmtime-{f}.json")
        if n and w:
            print(f"| `{f}` | {n['sourceBytes'] / 1024:.0f} KB | {fmt(n['compileMs'])} ms ({n['compileMBps']} MB/s) | {fmt(n['bytecodeLoadMs'])} ms "
                  f"| {fmt(w['compileMs'])} ms ({w['compileMBps']} MB/s) | {fmt(w['bytecodeLoadMs'])} ms |")

    print("\n### Guest-to-host call cost\n")
    print("| Runtime, host-function API | empty call | call passing a 16-byte string | empty loop iteration |")
    print("|---|---:|---:|---:|")
    labels = {
        "wasmtime": "wasmtime, `wasmtime_linker_define_func`",
        "wasmtime-unchecked": "wasmtime, `wasmtime_linker_define_func_unchecked`",
        "wamr-fastjit": "WAMR fast JIT, native library",
        "wamr-interp": "WAMR interpreter, native library",
    }
    for e, label in labels.items():
        r = load(runs / f"hostcall-{e}.json")
        if r:
            print(f"| {label} | {r['noop_ns']:.1f} ns | {r['set_prop_ns']:.1f} ns | {r['empty_loop_ns']:.1f} ns |")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/ultraweb-feasibility/runs")
