// Tests/UltraNet/ApiStatus/ProbeServer.h
// In-process HTTP/1.1 + WebSocket origin server used by the API status probes.
//
// It is written on top of UltraNet's own TCP surface (UltraNet_TcpListen /
// TcpAccept / TcpSend / TcpReceive), which means the status tool needs no
// Python, no external service, and no internet access to turn most of the
// HTTP / Session / SSE / WebSocket surface into verified WORKING entries. It
// also means the server itself is a live exercise of the TCP API — if TCP is
// broken, the server fails to start and the probes that depend on it say so
// instead of silently reporting "unverified".
//
// Routes (all under http://127.0.0.1:<port>):
//   GET    /hello          200 text/plain, fixed body
//   GET    /bytes/<n>      200 application/octet-stream, n generated bytes
//   ANY    /echo           200, echoes the request body; reflects the method
//                          in x-echo-method and the X-Probe request header in
//                          x-echo-probe
//   GET    /redirect       302 -> /hello
//   GET    /status/<code>  the given status code, empty body
//   GET    /setcookie      200 with Set-Cookie: ultranet_probe=chocolate
//   GET    /cookie         200, body "cookie=<value>" or "cookie=none"
//   GET    /auth           401 without Authorization, else 200 "auth=<value>"
//   GET    /sse            200 text/event-stream, four spec-shaped events
//   GET    /slow           200, dribbles bytes for ~10s (cancellation target)
//   GET    /ws             WebSocket upgrade; echoes text/binary, pongs pings
//
// Version: 0.1.0
// Author: UltraCanvas Framework / ULTRA OS
#pragma once

#include <UltraNet/UltraNetCore.h>

#include <atomic>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

namespace ultranet_apistatus {

class LoopbackServer {
public:
    static LoopbackServer& Instance();

    // Binds an ephemeral loopback port and starts the accept loop. Idempotent;
    // returns false (with Error() set) when no port could be bound.
    bool Start();
    void Stop();

    bool Running() const { return running_.load(std::memory_order_acquire); }
    int  Port()    const { return port_; }
    const std::string& Error() const { return error_; }

    // "http://127.0.0.1:<port><path>" / "ws://127.0.0.1:<port><path>".
    std::string Url(const std::string& path) const;
    std::string WsUrl(const std::string& path) const;

    // Number of HTTP requests served since Start(). Probes use the delta to
    // confirm a request actually reached the origin (rather than, say, being
    // answered from a cache or short-circuited).
    long RequestCount() const { return requestCount_.load(std::memory_order_acquire); }

    ~LoopbackServer();

private:
    LoopbackServer() = default;
    LoopbackServer(const LoopbackServer&) = delete;
    LoopbackServer& operator=(const LoopbackServer&) = delete;

    void AcceptLoop();
    void HandleConnection(UltraNetHandle conn);

    UltraNetHandle    listener_ = UltraNetInvalidHandle;
    int               port_ = 0;
    std::string       error_;
    std::atomic<bool> running_{false};
    std::atomic<bool> stop_{false};
    std::atomic<long> requestCount_{0};

    std::thread              acceptThread_;
    std::mutex               workersMutex_;
    std::vector<std::thread> workers_;
};

// Convenience for probe bodies: starts the server on first use and returns it.
// Probes that need the origin should check Running() and degrade to
// Implemented("...") rather than Broken when it could not be started.
LoopbackServer& Loopback();

} // namespace ultranet_apistatus
