# cmake/UltraCanvasAppIcon.cmake
# Reusable CMake function to embed an application icon in a Windows executable.
# Converts a source PNG to a multi-resolution .ico using ImageMagick,
# generates a .rc resource file, and links it into the target.

function(ultracanvas_embed_app_icon TARGET_NAME ICON_PNG_PATH)
    if(NOT WIN32)
        return()
    endif()

    # Find ImageMagick (try 'magick' first, then legacy 'convert')
    find_program(IMAGEMAGICK_CONVERT magick convert)
    if(NOT IMAGEMAGICK_CONVERT)
        message(WARNING "ImageMagick not found - skipping embedded icon for ${TARGET_NAME}. "
                        "Install ImageMagick to embed app icons in .exe files.")
        return()
    endif()

    # Output directory per target to avoid collisions
    set(ICON_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}_icon")
    set(ICON_ICO_PATH "${ICON_OUTPUT_DIR}/appicon.ico")
    set(ICON_RC_PATH "${ICON_OUTPUT_DIR}/appicon_resource.rc")

    # Create output directory
    file(MAKE_DIRECTORY ${ICON_OUTPUT_DIR})

    # Custom command: convert PNG to multi-resolution .ico (256, 48, 32, 16)
    add_custom_command(
        OUTPUT "${ICON_ICO_PATH}"
        COMMAND "${IMAGEMAGICK_CONVERT}"
            "${ICON_PNG_PATH}"
            -define icon:auto-resize=256,48,32,16
            "${ICON_ICO_PATH}"
        DEPENDS "${ICON_PNG_PATH}"
        COMMENT "Generating app icon .ico for ${TARGET_NAME} from ${ICON_PNG_PATH}"
        VERBATIM
    )

    # Generate the .rc file referencing the .ico
    file(WRITE "${ICON_RC_PATH}"
        "// Auto-generated by UltraCanvasAppIcon.cmake - do not edit\n"
        "#define IDI_UCAPP_ICON 101\n"
        "IDI_UCAPP_ICON ICON \"appicon.ico\"\n"
    )

    # Set include path for the resource compiler so it finds appicon.ico
    set_source_files_properties("${ICON_RC_PATH}" PROPERTIES
        COMPILE_FLAGS "-I\"${ICON_OUTPUT_DIR}\""
    )

    # Add the .rc and .ico to the target
    target_sources(${TARGET_NAME} PRIVATE
        "${ICON_RC_PATH}"
        "${ICON_ICO_PATH}"
    )

    message(STATUS "  Embedded app icon configured for ${TARGET_NAME}: ${ICON_PNG_PATH}")
endfunction()
