# cmake/UltraCanvasWinManifest.cmake
# Reusable CMake function to embed a Windows application manifest into an
# executable target. The manifest opts the process into the UTF-8 active code
# page (Windows 10 1903+ / Windows 11), so narrow (ANSI) Win32 and CRT calls —
# including those inside third-party libraries (fontconfig, FreeType, cairo,
# ...) — interpret file paths as UTF-8. Without it, paths containing
# characters outside the legacy system code page (Thai, CJK, ...) are mangled
# to '?' and every asset load under such a directory fails.
#
# NOTE: targets that ship their own manifest (e.g. UltraTexter) must NOT call
# this — two RT_MANIFEST resources with ID 1 fail at resource link time.
# DPI awareness is intentionally not declared here: UltraCanvas sets it
# programmatically (SetProcessDpiAwarenessContext) at startup.

function(ultracanvas_embed_windows_manifest TARGET_NAME)
    if(NOT WIN32)
        return()
    endif()

    set(MANIFEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}_manifest")
    file(MAKE_DIRECTORY "${MANIFEST_DIR}")
    set(MANIFEST_PATH "${MANIFEST_DIR}/app.manifest")
    set(MANIFEST_RC_PATH "${MANIFEST_DIR}/app_manifest.rc")

    file(WRITE "${MANIFEST_PATH}"
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
<assembly xmlns=\"urn:schemas-microsoft-com:asm.v1\" manifestVersion=\"1.0\">
    <assemblyIdentity
        version=\"1.0.0.0\"
        processorArchitecture=\"*\"
        name=\"UltraCanvas.${TARGET_NAME}\"
        type=\"win32\"
    />
    <trustInfo xmlns=\"urn:schemas-microsoft-com:asm.v3\">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level=\"asInvoker\" uiAccess=\"false\"/>
            </requestedPrivileges>
        </security>
    </trustInfo>
    <application xmlns=\"urn:schemas-microsoft-com:asm.v3\">
        <windowsSettings>
            <activeCodePage xmlns=\"http://schemas.microsoft.com/SMI/2019/WindowsSettings\">UTF-8</activeCodePage>
            <longPathAware xmlns=\"http://schemas.microsoft.com/SMI/2016/WindowsSettings\">true</longPathAware>
        </windowsSettings>
    </application>
    <compatibility xmlns=\"urn:schemas-microsoft-com:compatibility.v1\">
        <application>
            <!-- Windows 10 and 11 -->
            <supportedOS Id=\"{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}\"/>
            <!-- Windows 8.1 -->
            <supportedOS Id=\"{1f676c76-80e1-4239-95bb-83d0f6d0da78}\"/>
        </application>
    </compatibility>
</assembly>
")

    file(WRITE "${MANIFEST_RC_PATH}"
        "// Auto-generated by UltraCanvasWinManifest.cmake - do not edit\n"
        "#include <windows.h>\n"
        "1 RT_MANIFEST \"app.manifest\"\n"
    )

    # Resource compiler resolves the manifest relative to the .rc directory
    set_source_files_properties("${MANIFEST_RC_PATH}" PROPERTIES
        COMPILE_FLAGS "-I\"${MANIFEST_DIR}\""
    )

    target_sources(${TARGET_NAME} PRIVATE "${MANIFEST_RC_PATH}")

    message(STATUS "  Embedded Windows manifest (UTF-8 code page) for ${TARGET_NAME}")
endfunction()
