// include/UltraCrypt/UltraCryptCore.h
// Cryptographic services for the ULTRA OS / UltraCanvas framework.
//
// UltraCrypt is the single place where hashing, message authentication,
// authenticated encryption, key derivation and secure random generation are
// implemented, so that no application, plugin or sibling module has to write
// its own. The backing library (libsodium) is wrapped completely: no libsodium
// type appears in this header, so it can be replaced without affecting callers.
//
// Design rules (see Docs/Modules/UltraCrypt/README.md):
//  - AEAD only. No raw block-cipher or unauthenticated mode is exposed, so a
//    caller cannot accidentally ship unauthenticated ciphertext.
//  - Nonces are generated by the module by default; reuse must be opted into.
//  - The CSPRNG never falls back to a PRNG: entropy failure is an error.
//  - Secrets travel in UltraCryptSecureBuffer (move-only, zeroized on
//    destruction), never in std::string.
//  - Nothing throws. Every fallible operation returns UltraCryptResult.
//  - There is NO silent-passthrough fallback. If the backend is missing, every
//    operation fails with BackendUnavailable; nothing ever returns success
//    while leaving data unprotected.
//
// One cipher, one KDF: everything UltraCanvas writes uses XChaCha20-Poly1305
// keyed with Argon2id. AES-256-GCM exists only to read foreign data and is
// hardware-gated.
//
// Version: 0.1.0
// Author: UltraCanvas Framework / ULTRA OS
#pragma once
#ifndef ULTRACRYPTCORE_H
#define ULTRACRYPTCORE_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

// ============================================================================
// Result
// ============================================================================
enum class UltraCryptResultCode : uint8_t {
    Success,
    NotSupported,          // algorithm not available in this build / on this CPU
    InvalidArgument,
    InvalidKeySize,
    InvalidNonceSize,
    AuthenticationFailed,  // AEAD tag mismatch: ciphertext, AAD or nonce altered
    EntropyFailure,        // CSPRNG unavailable; never falls back to a PRNG
    BackendUnavailable,    // built without libsodium
    InternalError
};

// Returned by every blocking UltraCrypt_* call. operator bool() reports success
// for `if (UltraCrypt_Hash(...))` style checks.
//
// `message` is for developers and logs. It never contains key material,
// plaintext or password-derived data, and it never distinguishes *why* an AEAD
// open failed beyond AuthenticationFailed — that distinction is an oracle.
struct UltraCryptResult {
    UltraCryptResultCode code = UltraCryptResultCode::InternalError;
    bool success = false;
    std::string message;

    operator bool() const { return success; }

    static UltraCryptResult Ok();
    static UltraCryptResult Error(UltraCryptResultCode code,
                                  const std::string& message);
};

// ============================================================================
// Lifecycle
// ============================================================================
// Idempotent and thread-safe. Called automatically on first use; callers that
// care about deterministic initialisation order may call it explicitly.
UltraCryptResult UltraCrypt_Initialize();
void             UltraCrypt_Shutdown();
bool             UltraCrypt_IsAvailable();
std::string      UltraCrypt_GetBackendName();   // e.g. "libsodium 1.0.18"

// ============================================================================
// UltraCryptSecureBuffer — the type secrets travel in
// ============================================================================
// Move-only so a secret is never copied by accident, and zeroized on
// destruction so it does not linger in freed heap pages.
class UltraCryptSecureBuffer {
public:
    UltraCryptSecureBuffer() = default;
    explicit UltraCryptSecureBuffer(size_t size);            // zero-filled
    UltraCryptSecureBuffer(const void* data, size_t size);
    ~UltraCryptSecureBuffer();

    UltraCryptSecureBuffer(UltraCryptSecureBuffer&& other) noexcept;
    UltraCryptSecureBuffer& operator=(UltraCryptSecureBuffer&& other) noexcept;
    UltraCryptSecureBuffer(const UltraCryptSecureBuffer&) = delete;
    UltraCryptSecureBuffer& operator=(const UltraCryptSecureBuffer&) = delete;

    // Copying a secret must be deliberate.
    UltraCryptSecureBuffer Clone() const;

    uint8_t*       Data()       { return data_; }
    const uint8_t* Data() const { return data_; }
    size_t         GetSize() const { return size_; }
    bool           IsEmpty() const { return size_ == 0; }

    void Resize(size_t size);   // wipes any discarded bytes
    void Clear();               // zeroize and release

    // Best-effort mlock()/VirtualLock(): keeps pages out of swap. Returns false
    // when the OS refuses (e.g. RLIMIT_MEMLOCK) — a hint, never a guarantee.
    bool LockPages();

    // Adopts the bytes of a std::string and wipes the source in place, for
    // bridging from UI text fields that cannot hand over a secure buffer.
    static UltraCryptSecureBuffer AdoptString(std::string& text);

private:
    void Release();

    uint8_t* data_   = nullptr;
    size_t   size_   = 0;
    bool     locked_ = false;
};

// Compiler-barrier-protected wipe; not elided by the optimizer.
void UltraCrypt_SecureZero(void* data, size_t size);

// Length-independent comparison. Use for every MAC / tag / digest check.
// Returns false when sizes differ.
bool UltraCrypt_ConstantTimeEquals(const void* a, size_t aSize,
                                   const void* b, size_t bSize);

// ============================================================================
// Hashing
// ============================================================================
enum class UltraCryptHashAlgorithm : uint8_t {
    SHA256,
    SHA512
};

size_t UltraCrypt_GetDigestSize(UltraCryptHashAlgorithm algorithm);
bool   UltraCrypt_IsHashAvailable(UltraCryptHashAlgorithm algorithm);

UltraCryptResult UltraCrypt_Hash(UltraCryptHashAlgorithm algorithm,
                                 const void* data, size_t size,
                                 std::vector<uint8_t>& outDigest);

UltraCryptResult UltraCrypt_HashFile(UltraCryptHashAlgorithm algorithm,
                                     const std::string& filePath,
                                     std::vector<uint8_t>& outDigest);

std::string UltraCrypt_ToHex(const std::vector<uint8_t>& bytes);
bool        UltraCrypt_FromHex(const std::string& hex,
                               std::vector<uint8_t>& outBytes);

// Streaming hash, for files and large payloads.
class UltraCryptHasher {
public:
    explicit UltraCryptHasher(UltraCryptHashAlgorithm algorithm);
    ~UltraCryptHasher();
    UltraCryptHasher(const UltraCryptHasher&) = delete;
    UltraCryptHasher& operator=(const UltraCryptHasher&) = delete;

    void Update(const void* data, size_t size);
    // Finalises and returns the digest; Reset() to reuse.
    std::vector<uint8_t> Final();
    void Reset();

    size_t GetDigestSize() const;
    bool   IsValid() const { return state_ != nullptr; }

private:
    UltraCryptHashAlgorithm algorithm_;
    void* state_ = nullptr;
};

// ============================================================================
// HMAC
// ============================================================================
// Accepts keys of any length (the standard HMAC key schedule is applied).
UltraCryptResult UltraCrypt_Hmac(UltraCryptHashAlgorithm algorithm,
                                 const UltraCryptSecureBuffer& key,
                                 const void* data, size_t size,
                                 std::vector<uint8_t>& outMac);

// ============================================================================
// Authenticated encryption (AEAD)
// ============================================================================
enum class UltraCryptAeadAlgorithm : uint8_t {
    // The default, and the only cipher UltraCanvas ever writes. 192-bit nonce,
    // so randomly generated nonces are safe without bookkeeping; constant-time
    // in portable software on hardware without AES acceleration.
    XChaCha20Poly1305,

    // Interop only — for reading data produced elsewhere. Hardware-gated:
    // UltraCrypt_IsAeadAvailable returns false without AES-NI. Never select
    // this for new output.
    Aes256Gcm
};

struct UltraCryptAeadParams {
    UltraCryptAeadAlgorithm algorithm =
        UltraCryptAeadAlgorithm::XChaCha20Poly1305;

    // Seal: if empty, a fresh random nonce is generated and written back here
    // — the caller must store it. Supplying a nonce is allowed, but then
    // keeping it unique per key is the caller's responsibility.
    // Open: must be the nonce used at Seal time.
    std::vector<uint8_t> nonce;

    // Authenticated but not encrypted. Put file/section headers here so that
    // editing them invalidates the tag.
    std::vector<uint8_t> associatedData;
};

size_t UltraCrypt_GetKeySize(UltraCryptAeadAlgorithm algorithm);    // 32 both
size_t UltraCrypt_GetNonceSize(UltraCryptAeadAlgorithm algorithm);  // 24 / 12
size_t UltraCrypt_GetTagSize(UltraCryptAeadAlgorithm algorithm);    // 16
bool   UltraCrypt_IsAeadAvailable(UltraCryptAeadAlgorithm algorithm);

// Ciphertext is plaintext-length + tag size; the tag is appended.
UltraCryptResult UltraCrypt_AeadSeal(const UltraCryptSecureBuffer& key,
                                     UltraCryptAeadParams& params,
                                     const void* plaintext, size_t size,
                                     std::vector<uint8_t>& outCiphertext);

// Returns AuthenticationFailed — and leaves outPlaintext empty — if the
// ciphertext, the AAD or the nonce was altered. Never returns partially
// verified plaintext.
UltraCryptResult UltraCrypt_AeadOpen(const UltraCryptSecureBuffer& key,
                                     const UltraCryptAeadParams& params,
                                     const void* ciphertext, size_t size,
                                     UltraCryptSecureBuffer& outPlaintext);

// ============================================================================
// Key derivation
// ============================================================================
// One KDF. Argon2id is memory-hard, is the current standard (RFC 9106) and is
// what every UltraCanvas format and store uses. No alternative is offered: a
// second KDF would be a second code path in every reader for no benefit.
enum class UltraCryptKdfAlgorithm : uint8_t {
    Argon2id
};

size_t UltraCrypt_GetKdfSaltSize();     // 16

struct UltraCryptKdfParams {
    UltraCryptKdfAlgorithm algorithm = UltraCryptKdfAlgorithm::Argon2id;

    // If empty, UltraCrypt_DeriveKeyFromPassword generates a random salt of
    // UltraCrypt_GetKdfSaltSize() bytes and writes it back — the caller stores
    // it alongside the ciphertext.
    std::vector<uint8_t> salt;

    uint32_t iterations   = 0;   // Argon2id passes ("opslimit")
    uint32_t memoryKiB    = 0;   // Argon2id memory cost
    uint32_t parallelism  = 1;   // Argon2id lanes. The backing implementation
                                 // fixes this at 1; any other value is
                                 // rejected rather than silently ignored, so
                                 // stored parameters always mean what they say.
    size_t   outputLength = 32;
};

// Current-guidance cost parameters: 3 passes, 64 MiB, parallelism 1. These are
// revisited as hardware moves, so stored data must always record the parameters
// it was written with rather than assuming today's defaults — otherwise raising
// the defaults orphans every existing file.
UltraCryptKdfParams UltraCrypt_RecommendedKdfParams(
        UltraCryptKdfAlgorithm algorithm = UltraCryptKdfAlgorithm::Argon2id);

UltraCryptResult UltraCrypt_DeriveKeyFromPassword(
        const UltraCryptSecureBuffer& password,
        UltraCryptKdfParams& params,
        UltraCryptSecureBuffer& outKey);

// ============================================================================
// Random generation
// ============================================================================
// All draw from the OS CSPRNG. On failure they return EntropyFailure and leave
// the output untouched — there is deliberately no PRNG fallback.
UltraCryptResult UltraCrypt_RandomBytes(void* out, size_t size);
UltraCryptResult UltraCrypt_RandomBytes(std::vector<uint8_t>& out, size_t size);
UltraCryptResult UltraCrypt_RandomSecureBuffer(size_t size,
                                               UltraCryptSecureBuffer& out);

// Uniform in [0, bound) without modulo bias.
UltraCryptResult UltraCrypt_RandomUInt32(uint32_t bound, uint32_t& out);

// RFC 4122 version 4, lowercase hyphenated.
UltraCryptResult UltraCrypt_GenerateUuidV4(std::string& out);

#endif // ULTRACRYPTCORE_H
